# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: freeplane.proto for package 'freeplane'

require 'grpc'
require 'freeplane_pb'

module Freeplane
  module Freeplane
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'freeplane.Freeplane'

      rpc :CreateChild, CreateChildRequest, CreateChildResponse
      rpc :DeleteChild, DeleteChildRequest, DeleteChildResponse
      rpc :NodeAttributeAdd, NodeAttributeAddRequest, NodeAttributeAddResponse
      rpc :NodeLinkSet, NodeLinkSetRequest, NodeLinkSetResponse
      rpc :NodeDetailsSet, NodeDetailsSetRequest, NodeDetailsSetResponse
      rpc :NodeNoteSet, NodeNoteSetRequest, NodeNoteSetResponse
      rpc :NodeTagSet, NodeTagSetRequest, NodeTagSetResponse
      rpc :NodeTagAdd, NodeTagAddRequest, NodeTagAddResponse
      rpc :NodeConnect, NodeConnectRequest, NodeConnectResponse
      rpc :NodeAddIcon, NodeAddIconRequest, NodeAddIconResponse
      rpc :Groovy, GroovyRequest, GroovyResponse
      rpc :NodeColorSet, NodeColorSetRequest, NodeColorSetResponse
      rpc :NodeBackgroundColorSet, NodeBackgroundColorSetRequest, NodeBackgroundColorSetResponse
      rpc :StatusInfoSet, StatusInfoSetRequest, StatusInfoSetResponse
      rpc :TextFSM, TextFSMRequest, TextFSMResponse
      rpc :MindMapFromJSON, MindMapFromJSONRequest, MindMapFromJSONResponse
      rpc :MindMapToJSON, MindMapToJSONRequest, MindMapToJSONResponse
      rpc :GetCurrentNode, GetCurrentNodeRequest, GetCurrentNodeResponse
      rpc :OpenMap, OpenMapRequest, OpenMapResponse
      rpc :FocusNode, FocusNodeRequest, FocusNodeResponse
      rpc :GetNodeText, GetNodeTextRequest, GetNodeTextResponse
      rpc :GetParentNode, GetParentNodeRequest, GetParentNodeResponse
      rpc :ListChildNodes, ListChildNodesRequest, ListChildNodesResponse
      rpc :GetNodeNote, GetNodeNoteRequest, GetNodeNoteResponse
      rpc :GetNodeLink, GetNodeLinkRequest, GetNodeLinkResponse
      rpc :SetNodeText, SetNodeTextRequest, SetNodeTextResponse
      rpc :MoveNode, MoveNodeRequest, MoveNodeResponse
    end

    Stub = Service.rpc_stub_class
  end
end
