# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: freeplane.proto for package 'freeplane'

require 'grpc'
require 'freeplane_pb'

module Freeplane
  module Freeplane
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'freeplane.Freeplane'

      rpc :CreateChild, ::Freeplane::CreateChildRequest, ::Freeplane::CreateChildResponse
      rpc :DeleteChild, ::Freeplane::DeleteChildRequest, ::Freeplane::DeleteChildResponse
      rpc :NodeAttributeAdd, ::Freeplane::NodeAttributeAddRequest, ::Freeplane::NodeAttributeAddResponse
      rpc :NodeLinkSet, ::Freeplane::NodeLinkSetRequest, ::Freeplane::NodeLinkSetResponse
      rpc :NodeDetailsSet, ::Freeplane::NodeDetailsSetRequest, ::Freeplane::NodeDetailsSetResponse
      rpc :NodeNoteSet, ::Freeplane::NodeNoteSetRequest, ::Freeplane::NodeNoteSetResponse
      rpc :NodeTagSet, ::Freeplane::NodeTagSetRequest, ::Freeplane::NodeTagSetResponse
      rpc :NodeTagAdd, ::Freeplane::NodeTagAddRequest, ::Freeplane::NodeTagAddResponse
      rpc :NodeConnect, ::Freeplane::NodeConnectRequest, ::Freeplane::NodeConnectResponse
      rpc :NodeAddIcon, ::Freeplane::NodeAddIconRequest, ::Freeplane::NodeAddIconResponse
      rpc :Groovy, ::Freeplane::GroovyRequest, ::Freeplane::GroovyResponse
      rpc :NodeColorSet, ::Freeplane::NodeColorSetRequest, ::Freeplane::NodeColorSetResponse
      rpc :NodeBackgroundColorSet, ::Freeplane::NodeBackgroundColorSetRequest, ::Freeplane::NodeBackgroundColorSetResponse
      rpc :StatusInfoSet, ::Freeplane::StatusInfoSetRequest, ::Freeplane::StatusInfoSetResponse
      rpc :TextFSM, ::Freeplane::TextFSMRequest, ::Freeplane::TextFSMResponse
      rpc :MindMapFromJSON, ::Freeplane::MindMapFromJSONRequest, ::Freeplane::MindMapFromJSONResponse
      rpc :MindMapToJSON, ::Freeplane::MindMapToJSONRequest, ::Freeplane::MindMapToJSONResponse
      rpc :GetCurrentNode, ::Freeplane::GetCurrentNodeRequest, ::Freeplane::GetCurrentNodeResponse
      rpc :OpenMap, ::Freeplane::OpenMapRequest, ::Freeplane::OpenMapResponse
      rpc :FocusNode, ::Freeplane::FocusNodeRequest, ::Freeplane::FocusNodeResponse
      # --- Group A: Node Inspection ---
      #
      rpc :GetNodeText, ::Freeplane::GetNodeTextRequest, ::Freeplane::GetNodeTextResponse
      rpc :GetParentNode, ::Freeplane::GetParentNodeRequest, ::Freeplane::GetParentNodeResponse
      rpc :ListChildNodes, ::Freeplane::ListChildNodesRequest, ::Freeplane::ListChildNodesResponse
      rpc :GetNodeNote, ::Freeplane::GetNodeNoteRequest, ::Freeplane::GetNodeNoteResponse
      rpc :GetNodeLink, ::Freeplane::GetNodeLinkRequest, ::Freeplane::GetNodeLinkResponse
      # --- Group B: Node Manipulation ---
      #
      rpc :SetNodeText, ::Freeplane::SetNodeTextRequest, ::Freeplane::SetNodeTextResponse
      rpc :MoveNode, ::Freeplane::MoveNodeRequest, ::Freeplane::MoveNodeResponse
    end

    Stub = Service.rpc_stub_class
  end
end
