// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: freeplane.proto

package freeplane

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Freeplane_CreateChild_FullMethodName            = "/freeplane.Freeplane/CreateChild"
	Freeplane_DeleteChild_FullMethodName            = "/freeplane.Freeplane/DeleteChild"
	Freeplane_NodeAttributeAdd_FullMethodName       = "/freeplane.Freeplane/NodeAttributeAdd"
	Freeplane_NodeLinkSet_FullMethodName            = "/freeplane.Freeplane/NodeLinkSet"
	Freeplane_NodeDetailsSet_FullMethodName         = "/freeplane.Freeplane/NodeDetailsSet"
	Freeplane_NodeNoteSet_FullMethodName            = "/freeplane.Freeplane/NodeNoteSet"
	Freeplane_NodeTagSet_FullMethodName             = "/freeplane.Freeplane/NodeTagSet"
	Freeplane_NodeTagAdd_FullMethodName             = "/freeplane.Freeplane/NodeTagAdd"
	Freeplane_NodeConnect_FullMethodName            = "/freeplane.Freeplane/NodeConnect"
	Freeplane_NodeAddIcon_FullMethodName            = "/freeplane.Freeplane/NodeAddIcon"
	Freeplane_Groovy_FullMethodName                 = "/freeplane.Freeplane/Groovy"
	Freeplane_NodeColorSet_FullMethodName           = "/freeplane.Freeplane/NodeColorSet"
	Freeplane_NodeBackgroundColorSet_FullMethodName = "/freeplane.Freeplane/NodeBackgroundColorSet"
	Freeplane_StatusInfoSet_FullMethodName          = "/freeplane.Freeplane/StatusInfoSet"
	Freeplane_TextFSM_FullMethodName                = "/freeplane.Freeplane/TextFSM"
	Freeplane_MindMapFromJSON_FullMethodName        = "/freeplane.Freeplane/MindMapFromJSON"
	Freeplane_MindMapToJSON_FullMethodName          = "/freeplane.Freeplane/MindMapToJSON"
	Freeplane_GetCurrentNode_FullMethodName         = "/freeplane.Freeplane/GetCurrentNode"
	Freeplane_OpenMap_FullMethodName                = "/freeplane.Freeplane/OpenMap"
	Freeplane_FocusNode_FullMethodName              = "/freeplane.Freeplane/FocusNode"
	Freeplane_GetNodeText_FullMethodName            = "/freeplane.Freeplane/GetNodeText"
	Freeplane_GetParentNode_FullMethodName          = "/freeplane.Freeplane/GetParentNode"
	Freeplane_ListChildNodes_FullMethodName         = "/freeplane.Freeplane/ListChildNodes"
	Freeplane_GetNodeNote_FullMethodName            = "/freeplane.Freeplane/GetNodeNote"
	Freeplane_GetNodeLink_FullMethodName            = "/freeplane.Freeplane/GetNodeLink"
	Freeplane_SetNodeText_FullMethodName            = "/freeplane.Freeplane/SetNodeText"
	Freeplane_MoveNode_FullMethodName               = "/freeplane.Freeplane/MoveNode"
)

// FreeplaneClient is the client API for Freeplane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FreeplaneClient interface {
	CreateChild(ctx context.Context, in *CreateChildRequest, opts ...grpc.CallOption) (*CreateChildResponse, error)
	DeleteChild(ctx context.Context, in *DeleteChildRequest, opts ...grpc.CallOption) (*DeleteChildResponse, error)
	NodeAttributeAdd(ctx context.Context, in *NodeAttributeAddRequest, opts ...grpc.CallOption) (*NodeAttributeAddResponse, error)
	NodeLinkSet(ctx context.Context, in *NodeLinkSetRequest, opts ...grpc.CallOption) (*NodeLinkSetResponse, error)
	NodeDetailsSet(ctx context.Context, in *NodeDetailsSetRequest, opts ...grpc.CallOption) (*NodeDetailsSetResponse, error)
	NodeNoteSet(ctx context.Context, in *NodeNoteSetRequest, opts ...grpc.CallOption) (*NodeNoteSetResponse, error)
	NodeTagSet(ctx context.Context, in *NodeTagSetRequest, opts ...grpc.CallOption) (*NodeTagSetResponse, error)
	NodeTagAdd(ctx context.Context, in *NodeTagAddRequest, opts ...grpc.CallOption) (*NodeTagAddResponse, error)
	NodeConnect(ctx context.Context, in *NodeConnectRequest, opts ...grpc.CallOption) (*NodeConnectResponse, error)
	NodeAddIcon(ctx context.Context, in *NodeAddIconRequest, opts ...grpc.CallOption) (*NodeAddIconResponse, error)
	Groovy(ctx context.Context, in *GroovyRequest, opts ...grpc.CallOption) (*GroovyResponse, error)
	NodeColorSet(ctx context.Context, in *NodeColorSetRequest, opts ...grpc.CallOption) (*NodeColorSetResponse, error)
	NodeBackgroundColorSet(ctx context.Context, in *NodeBackgroundColorSetRequest, opts ...grpc.CallOption) (*NodeBackgroundColorSetResponse, error)
	StatusInfoSet(ctx context.Context, in *StatusInfoSetRequest, opts ...grpc.CallOption) (*StatusInfoSetResponse, error)
	TextFSM(ctx context.Context, in *TextFSMRequest, opts ...grpc.CallOption) (*TextFSMResponse, error)
	MindMapFromJSON(ctx context.Context, in *MindMapFromJSONRequest, opts ...grpc.CallOption) (*MindMapFromJSONResponse, error)
	MindMapToJSON(ctx context.Context, in *MindMapToJSONRequest, opts ...grpc.CallOption) (*MindMapToJSONResponse, error)
	GetCurrentNode(ctx context.Context, in *GetCurrentNodeRequest, opts ...grpc.CallOption) (*GetCurrentNodeResponse, error)
	OpenMap(ctx context.Context, in *OpenMapRequest, opts ...grpc.CallOption) (*OpenMapResponse, error)
	FocusNode(ctx context.Context, in *FocusNodeRequest, opts ...grpc.CallOption) (*FocusNodeResponse, error)
	GetNodeText(ctx context.Context, in *GetNodeTextRequest, opts ...grpc.CallOption) (*GetNodeTextResponse, error)
	GetParentNode(ctx context.Context, in *GetParentNodeRequest, opts ...grpc.CallOption) (*GetParentNodeResponse, error)
	ListChildNodes(ctx context.Context, in *ListChildNodesRequest, opts ...grpc.CallOption) (*ListChildNodesResponse, error)
	GetNodeNote(ctx context.Context, in *GetNodeNoteRequest, opts ...grpc.CallOption) (*GetNodeNoteResponse, error)
	GetNodeLink(ctx context.Context, in *GetNodeLinkRequest, opts ...grpc.CallOption) (*GetNodeLinkResponse, error)
	SetNodeText(ctx context.Context, in *SetNodeTextRequest, opts ...grpc.CallOption) (*SetNodeTextResponse, error)
	MoveNode(ctx context.Context, in *MoveNodeRequest, opts ...grpc.CallOption) (*MoveNodeResponse, error)
}

type freeplaneClient struct {
	cc grpc.ClientConnInterface
}

func NewFreeplaneClient(cc grpc.ClientConnInterface) FreeplaneClient {
	return &freeplaneClient{cc}
}

func (c *freeplaneClient) CreateChild(ctx context.Context, in *CreateChildRequest, opts ...grpc.CallOption) (*CreateChildResponse, error) {
	out := new(CreateChildResponse)
	err := c.cc.Invoke(ctx, Freeplane_CreateChild_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freeplaneClient) DeleteChild(ctx context.Context, in *DeleteChildRequest, opts ...grpc.CallOption) (*DeleteChildResponse, error) {
	out := new(DeleteChildResponse)
	err := c.cc.Invoke(ctx, Freeplane_DeleteChild_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freeplaneClient) NodeAttributeAdd(ctx context.Context, in *NodeAttributeAddRequest, opts ...grpc.CallOption) (*NodeAttributeAddResponse, error) {
	out := new(NodeAttributeAddResponse)
	err := c.cc.Invoke(ctx, Freeplane_NodeAttributeAdd_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freeplaneClient) NodeLinkSet(ctx context.Context, in *NodeLinkSetRequest, opts ...grpc.CallOption) (*NodeLinkSetResponse, error) {
	out := new(NodeLinkSetResponse)
	err := c.cc.Invoke(ctx, Freeplane_NodeLinkSet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freeplaneClient) NodeDetailsSet(ctx context.Context, in *NodeDetailsSetRequest, opts ...grpc.CallOption) (*NodeDetailsSetResponse, error) {
	out := new(NodeDetailsSetResponse)
	err := c.cc.Invoke(ctx, Freeplane_NodeDetailsSet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freeplaneClient) NodeNoteSet(ctx context.Context, in *NodeNoteSetRequest, opts ...grpc.CallOption) (*NodeNoteSetResponse, error) {
	out := new(NodeNoteSetResponse)
	err := c.cc.Invoke(ctx, Freeplane_NodeNoteSet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freeplaneClient) NodeTagSet(ctx context.Context, in *NodeTagSetRequest, opts ...grpc.CallOption) (*NodeTagSetResponse, error) {
	out := new(NodeTagSetResponse)
	err := c.cc.Invoke(ctx, Freeplane_NodeTagSet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freeplaneClient) NodeTagAdd(ctx context.Context, in *NodeTagAddRequest, opts ...grpc.CallOption) (*NodeTagAddResponse, error) {
	out := new(NodeTagAddResponse)
	err := c.cc.Invoke(ctx, Freeplane_NodeTagAdd_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freeplaneClient) NodeConnect(ctx context.Context, in *NodeConnectRequest, opts ...grpc.CallOption) (*NodeConnectResponse, error) {
	out := new(NodeConnectResponse)
	err := c.cc.Invoke(ctx, Freeplane_NodeConnect_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freeplaneClient) NodeAddIcon(ctx context.Context, in *NodeAddIconRequest, opts ...grpc.CallOption) (*NodeAddIconResponse, error) {
	out := new(NodeAddIconResponse)
	err := c.cc.Invoke(ctx, Freeplane_NodeAddIcon_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freeplaneClient) Groovy(ctx context.Context, in *GroovyRequest, opts ...grpc.CallOption) (*GroovyResponse, error) {
	out := new(GroovyResponse)
	err := c.cc.Invoke(ctx, Freeplane_Groovy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freeplaneClient) NodeColorSet(ctx context.Context, in *NodeColorSetRequest, opts ...grpc.CallOption) (*NodeColorSetResponse, error) {
	out := new(NodeColorSetResponse)
	err := c.cc.Invoke(ctx, Freeplane_NodeColorSet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freeplaneClient) NodeBackgroundColorSet(ctx context.Context, in *NodeBackgroundColorSetRequest, opts ...grpc.CallOption) (*NodeBackgroundColorSetResponse, error) {
	out := new(NodeBackgroundColorSetResponse)
	err := c.cc.Invoke(ctx, Freeplane_NodeBackgroundColorSet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freeplaneClient) StatusInfoSet(ctx context.Context, in *StatusInfoSetRequest, opts ...grpc.CallOption) (*StatusInfoSetResponse, error) {
	out := new(StatusInfoSetResponse)
	err := c.cc.Invoke(ctx, Freeplane_StatusInfoSet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freeplaneClient) TextFSM(ctx context.Context, in *TextFSMRequest, opts ...grpc.CallOption) (*TextFSMResponse, error) {
	out := new(TextFSMResponse)
	err := c.cc.Invoke(ctx, Freeplane_TextFSM_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freeplaneClient) MindMapFromJSON(ctx context.Context, in *MindMapFromJSONRequest, opts ...grpc.CallOption) (*MindMapFromJSONResponse, error) {
	out := new(MindMapFromJSONResponse)
	err := c.cc.Invoke(ctx, Freeplane_MindMapFromJSON_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freeplaneClient) MindMapToJSON(ctx context.Context, in *MindMapToJSONRequest, opts ...grpc.CallOption) (*MindMapToJSONResponse, error) {
	out := new(MindMapToJSONResponse)
	err := c.cc.Invoke(ctx, Freeplane_MindMapToJSON_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freeplaneClient) GetCurrentNode(ctx context.Context, in *GetCurrentNodeRequest, opts ...grpc.CallOption) (*GetCurrentNodeResponse, error) {
	out := new(GetCurrentNodeResponse)
	err := c.cc.Invoke(ctx, Freeplane_GetCurrentNode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freeplaneClient) OpenMap(ctx context.Context, in *OpenMapRequest, opts ...grpc.CallOption) (*OpenMapResponse, error) {
	out := new(OpenMapResponse)
	err := c.cc.Invoke(ctx, Freeplane_OpenMap_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freeplaneClient) FocusNode(ctx context.Context, in *FocusNodeRequest, opts ...grpc.CallOption) (*FocusNodeResponse, error) {
	out := new(FocusNodeResponse)
	err := c.cc.Invoke(ctx, Freeplane_FocusNode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freeplaneClient) GetNodeText(ctx context.Context, in *GetNodeTextRequest, opts ...grpc.CallOption) (*GetNodeTextResponse, error) {
	out := new(GetNodeTextResponse)
	err := c.cc.Invoke(ctx, Freeplane_GetNodeText_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freeplaneClient) GetParentNode(ctx context.Context, in *GetParentNodeRequest, opts ...grpc.CallOption) (*GetParentNodeResponse, error) {
	out := new(GetParentNodeResponse)
	err := c.cc.Invoke(ctx, Freeplane_GetParentNode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freeplaneClient) ListChildNodes(ctx context.Context, in *ListChildNodesRequest, opts ...grpc.CallOption) (*ListChildNodesResponse, error) {
	out := new(ListChildNodesResponse)
	err := c.cc.Invoke(ctx, Freeplane_ListChildNodes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freeplaneClient) GetNodeNote(ctx context.Context, in *GetNodeNoteRequest, opts ...grpc.CallOption) (*GetNodeNoteResponse, error) {
	out := new(GetNodeNoteResponse)
	err := c.cc.Invoke(ctx, Freeplane_GetNodeNote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freeplaneClient) GetNodeLink(ctx context.Context, in *GetNodeLinkRequest, opts ...grpc.CallOption) (*GetNodeLinkResponse, error) {
	out := new(GetNodeLinkResponse)
	err := c.cc.Invoke(ctx, Freeplane_GetNodeLink_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freeplaneClient) SetNodeText(ctx context.Context, in *SetNodeTextRequest, opts ...grpc.CallOption) (*SetNodeTextResponse, error) {
	out := new(SetNodeTextResponse)
	err := c.cc.Invoke(ctx, Freeplane_SetNodeText_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freeplaneClient) MoveNode(ctx context.Context, in *MoveNodeRequest, opts ...grpc.CallOption) (*MoveNodeResponse, error) {
	out := new(MoveNodeResponse)
	err := c.cc.Invoke(ctx, Freeplane_MoveNode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FreeplaneServer is the server API for Freeplane service.
// All implementations must embed UnimplementedFreeplaneServer
// for forward compatibility
type FreeplaneServer interface {
	CreateChild(context.Context, *CreateChildRequest) (*CreateChildResponse, error)
	DeleteChild(context.Context, *DeleteChildRequest) (*DeleteChildResponse, error)
	NodeAttributeAdd(context.Context, *NodeAttributeAddRequest) (*NodeAttributeAddResponse, error)
	NodeLinkSet(context.Context, *NodeLinkSetRequest) (*NodeLinkSetResponse, error)
	NodeDetailsSet(context.Context, *NodeDetailsSetRequest) (*NodeDetailsSetResponse, error)
	NodeNoteSet(context.Context, *NodeNoteSetRequest) (*NodeNoteSetResponse, error)
	NodeTagSet(context.Context, *NodeTagSetRequest) (*NodeTagSetResponse, error)
	NodeTagAdd(context.Context, *NodeTagAddRequest) (*NodeTagAddResponse, error)
	NodeConnect(context.Context, *NodeConnectRequest) (*NodeConnectResponse, error)
	NodeAddIcon(context.Context, *NodeAddIconRequest) (*NodeAddIconResponse, error)
	Groovy(context.Context, *GroovyRequest) (*GroovyResponse, error)
	NodeColorSet(context.Context, *NodeColorSetRequest) (*NodeColorSetResponse, error)
	NodeBackgroundColorSet(context.Context, *NodeBackgroundColorSetRequest) (*NodeBackgroundColorSetResponse, error)
	StatusInfoSet(context.Context, *StatusInfoSetRequest) (*StatusInfoSetResponse, error)
	TextFSM(context.Context, *TextFSMRequest) (*TextFSMResponse, error)
	MindMapFromJSON(context.Context, *MindMapFromJSONRequest) (*MindMapFromJSONResponse, error)
	MindMapToJSON(context.Context, *MindMapToJSONRequest) (*MindMapToJSONResponse, error)
	GetCurrentNode(context.Context, *GetCurrentNodeRequest) (*GetCurrentNodeResponse, error)
	OpenMap(context.Context, *OpenMapRequest) (*OpenMapResponse, error)
	FocusNode(context.Context, *FocusNodeRequest) (*FocusNodeResponse, error)
	GetNodeText(context.Context, *GetNodeTextRequest) (*GetNodeTextResponse, error)
	GetParentNode(context.Context, *GetParentNodeRequest) (*GetParentNodeResponse, error)
	ListChildNodes(context.Context, *ListChildNodesRequest) (*ListChildNodesResponse, error)
	GetNodeNote(context.Context, *GetNodeNoteRequest) (*GetNodeNoteResponse, error)
	GetNodeLink(context.Context, *GetNodeLinkRequest) (*GetNodeLinkResponse, error)
	SetNodeText(context.Context, *SetNodeTextRequest) (*SetNodeTextResponse, error)
	MoveNode(context.Context, *MoveNodeRequest) (*MoveNodeResponse, error)
	mustEmbedUnimplementedFreeplaneServer()
}

// UnimplementedFreeplaneServer must be embedded to have forward compatible implementations.
type UnimplementedFreeplaneServer struct {
}

func (UnimplementedFreeplaneServer) CreateChild(context.Context, *CreateChildRequest) (*CreateChildResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateChild not implemented")
}
func (UnimplementedFreeplaneServer) DeleteChild(context.Context, *DeleteChildRequest) (*DeleteChildResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteChild not implemented")
}
func (UnimplementedFreeplaneServer) NodeAttributeAdd(context.Context, *NodeAttributeAddRequest) (*NodeAttributeAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeAttributeAdd not implemented")
}
func (UnimplementedFreeplaneServer) NodeLinkSet(context.Context, *NodeLinkSetRequest) (*NodeLinkSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeLinkSet not implemented")
}
func (UnimplementedFreeplaneServer) NodeDetailsSet(context.Context, *NodeDetailsSetRequest) (*NodeDetailsSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeDetailsSet not implemented")
}
func (UnimplementedFreeplaneServer) NodeNoteSet(context.Context, *NodeNoteSetRequest) (*NodeNoteSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeNoteSet not implemented")
}
func (UnimplementedFreeplaneServer) NodeTagSet(context.Context, *NodeTagSetRequest) (*NodeTagSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeTagSet not implemented")
}
func (UnimplementedFreeplaneServer) NodeTagAdd(context.Context, *NodeTagAddRequest) (*NodeTagAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeTagAdd not implemented")
}
func (UnimplementedFreeplaneServer) NodeConnect(context.Context, *NodeConnectRequest) (*NodeConnectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeConnect not implemented")
}
func (UnimplementedFreeplaneServer) NodeAddIcon(context.Context, *NodeAddIconRequest) (*NodeAddIconResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeAddIcon not implemented")
}
func (UnimplementedFreeplaneServer) Groovy(context.Context, *GroovyRequest) (*GroovyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Groovy not implemented")
}
func (UnimplementedFreeplaneServer) NodeColorSet(context.Context, *NodeColorSetRequest) (*NodeColorSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeColorSet not implemented")
}
func (UnimplementedFreeplaneServer) NodeBackgroundColorSet(context.Context, *NodeBackgroundColorSetRequest) (*NodeBackgroundColorSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeBackgroundColorSet not implemented")
}
func (UnimplementedFreeplaneServer) StatusInfoSet(context.Context, *StatusInfoSetRequest) (*StatusInfoSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StatusInfoSet not implemented")
}
func (UnimplementedFreeplaneServer) TextFSM(context.Context, *TextFSMRequest) (*TextFSMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TextFSM not implemented")
}
func (UnimplementedFreeplaneServer) MindMapFromJSON(context.Context, *MindMapFromJSONRequest) (*MindMapFromJSONResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MindMapFromJSON not implemented")
}
func (UnimplementedFreeplaneServer) MindMapToJSON(context.Context, *MindMapToJSONRequest) (*MindMapToJSONResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MindMapToJSON not implemented")
}
func (UnimplementedFreeplaneServer) GetCurrentNode(context.Context, *GetCurrentNodeRequest) (*GetCurrentNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentNode not implemented")
}
func (UnimplementedFreeplaneServer) OpenMap(context.Context, *OpenMapRequest) (*OpenMapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenMap not implemented")
}
func (UnimplementedFreeplaneServer) FocusNode(context.Context, *FocusNodeRequest) (*FocusNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FocusNode not implemented")
}
func (UnimplementedFreeplaneServer) GetNodeText(context.Context, *GetNodeTextRequest) (*GetNodeTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeText not implemented")
}
func (UnimplementedFreeplaneServer) GetParentNode(context.Context, *GetParentNodeRequest) (*GetParentNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetParentNode not implemented")
}
func (UnimplementedFreeplaneServer) ListChildNodes(context.Context, *ListChildNodesRequest) (*ListChildNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChildNodes not implemented")
}
func (UnimplementedFreeplaneServer) GetNodeNote(context.Context, *GetNodeNoteRequest) (*GetNodeNoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeNote not implemented")
}
func (UnimplementedFreeplaneServer) GetNodeLink(context.Context, *GetNodeLinkRequest) (*GetNodeLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeLink not implemented")
}
func (UnimplementedFreeplaneServer) SetNodeText(context.Context, *SetNodeTextRequest) (*SetNodeTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetNodeText not implemented")
}
func (UnimplementedFreeplaneServer) MoveNode(context.Context, *MoveNodeRequest) (*MoveNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveNode not implemented")
}
func (UnimplementedFreeplaneServer) mustEmbedUnimplementedFreeplaneServer() {}

// UnsafeFreeplaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FreeplaneServer will
// result in compilation errors.
type UnsafeFreeplaneServer interface {
	mustEmbedUnimplementedFreeplaneServer()
}

func RegisterFreeplaneServer(s grpc.ServiceRegistrar, srv FreeplaneServer) {
	s.RegisterService(&Freeplane_ServiceDesc, srv)
}

func _Freeplane_CreateChild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeplaneServer).CreateChild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Freeplane_CreateChild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeplaneServer).CreateChild(ctx, req.(*CreateChildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Freeplane_DeleteChild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeplaneServer).DeleteChild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Freeplane_DeleteChild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeplaneServer).DeleteChild(ctx, req.(*DeleteChildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Freeplane_NodeAttributeAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeAttributeAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeplaneServer).NodeAttributeAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Freeplane_NodeAttributeAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeplaneServer).NodeAttributeAdd(ctx, req.(*NodeAttributeAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Freeplane_NodeLinkSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeLinkSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeplaneServer).NodeLinkSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Freeplane_NodeLinkSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeplaneServer).NodeLinkSet(ctx, req.(*NodeLinkSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Freeplane_NodeDetailsSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeDetailsSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeplaneServer).NodeDetailsSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Freeplane_NodeDetailsSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeplaneServer).NodeDetailsSet(ctx, req.(*NodeDetailsSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Freeplane_NodeNoteSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeNoteSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeplaneServer).NodeNoteSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Freeplane_NodeNoteSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeplaneServer).NodeNoteSet(ctx, req.(*NodeNoteSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Freeplane_NodeTagSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeTagSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeplaneServer).NodeTagSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Freeplane_NodeTagSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeplaneServer).NodeTagSet(ctx, req.(*NodeTagSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Freeplane_NodeTagAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeTagAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeplaneServer).NodeTagAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Freeplane_NodeTagAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeplaneServer).NodeTagAdd(ctx, req.(*NodeTagAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Freeplane_NodeConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeplaneServer).NodeConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Freeplane_NodeConnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeplaneServer).NodeConnect(ctx, req.(*NodeConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Freeplane_NodeAddIcon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeAddIconRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeplaneServer).NodeAddIcon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Freeplane_NodeAddIcon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeplaneServer).NodeAddIcon(ctx, req.(*NodeAddIconRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Freeplane_Groovy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroovyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeplaneServer).Groovy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Freeplane_Groovy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeplaneServer).Groovy(ctx, req.(*GroovyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Freeplane_NodeColorSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeColorSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeplaneServer).NodeColorSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Freeplane_NodeColorSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeplaneServer).NodeColorSet(ctx, req.(*NodeColorSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Freeplane_NodeBackgroundColorSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeBackgroundColorSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeplaneServer).NodeBackgroundColorSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Freeplane_NodeBackgroundColorSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeplaneServer).NodeBackgroundColorSet(ctx, req.(*NodeBackgroundColorSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Freeplane_StatusInfoSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusInfoSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeplaneServer).StatusInfoSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Freeplane_StatusInfoSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeplaneServer).StatusInfoSet(ctx, req.(*StatusInfoSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Freeplane_TextFSM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextFSMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeplaneServer).TextFSM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Freeplane_TextFSM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeplaneServer).TextFSM(ctx, req.(*TextFSMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Freeplane_MindMapFromJSON_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MindMapFromJSONRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeplaneServer).MindMapFromJSON(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Freeplane_MindMapFromJSON_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeplaneServer).MindMapFromJSON(ctx, req.(*MindMapFromJSONRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Freeplane_MindMapToJSON_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MindMapToJSONRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeplaneServer).MindMapToJSON(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Freeplane_MindMapToJSON_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeplaneServer).MindMapToJSON(ctx, req.(*MindMapToJSONRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Freeplane_GetCurrentNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeplaneServer).GetCurrentNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Freeplane_GetCurrentNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeplaneServer).GetCurrentNode(ctx, req.(*GetCurrentNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Freeplane_OpenMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeplaneServer).OpenMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Freeplane_OpenMap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeplaneServer).OpenMap(ctx, req.(*OpenMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Freeplane_FocusNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FocusNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeplaneServer).FocusNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Freeplane_FocusNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeplaneServer).FocusNode(ctx, req.(*FocusNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Freeplane_GetNodeText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeplaneServer).GetNodeText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Freeplane_GetNodeText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeplaneServer).GetNodeText(ctx, req.(*GetNodeTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Freeplane_GetParentNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParentNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeplaneServer).GetParentNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Freeplane_GetParentNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeplaneServer).GetParentNode(ctx, req.(*GetParentNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Freeplane_ListChildNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChildNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeplaneServer).ListChildNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Freeplane_ListChildNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeplaneServer).ListChildNodes(ctx, req.(*ListChildNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Freeplane_GetNodeNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeplaneServer).GetNodeNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Freeplane_GetNodeNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeplaneServer).GetNodeNote(ctx, req.(*GetNodeNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Freeplane_GetNodeLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeplaneServer).GetNodeLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Freeplane_GetNodeLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeplaneServer).GetNodeLink(ctx, req.(*GetNodeLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Freeplane_SetNodeText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNodeTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeplaneServer).SetNodeText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Freeplane_SetNodeText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeplaneServer).SetNodeText(ctx, req.(*SetNodeTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Freeplane_MoveNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeplaneServer).MoveNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Freeplane_MoveNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeplaneServer).MoveNode(ctx, req.(*MoveNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Freeplane_ServiceDesc is the grpc.ServiceDesc for Freeplane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Freeplane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "freeplane.Freeplane",
	HandlerType: (*FreeplaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateChild",
			Handler:    _Freeplane_CreateChild_Handler,
		},
		{
			MethodName: "DeleteChild",
			Handler:    _Freeplane_DeleteChild_Handler,
		},
		{
			MethodName: "NodeAttributeAdd",
			Handler:    _Freeplane_NodeAttributeAdd_Handler,
		},
		{
			MethodName: "NodeLinkSet",
			Handler:    _Freeplane_NodeLinkSet_Handler,
		},
		{
			MethodName: "NodeDetailsSet",
			Handler:    _Freeplane_NodeDetailsSet_Handler,
		},
		{
			MethodName: "NodeNoteSet",
			Handler:    _Freeplane_NodeNoteSet_Handler,
		},
		{
			MethodName: "NodeTagSet",
			Handler:    _Freeplane_NodeTagSet_Handler,
		},
		{
			MethodName: "NodeTagAdd",
			Handler:    _Freeplane_NodeTagAdd_Handler,
		},
		{
			MethodName: "NodeConnect",
			Handler:    _Freeplane_NodeConnect_Handler,
		},
		{
			MethodName: "NodeAddIcon",
			Handler:    _Freeplane_NodeAddIcon_Handler,
		},
		{
			MethodName: "Groovy",
			Handler:    _Freeplane_Groovy_Handler,
		},
		{
			MethodName: "NodeColorSet",
			Handler:    _Freeplane_NodeColorSet_Handler,
		},
		{
			MethodName: "NodeBackgroundColorSet",
			Handler:    _Freeplane_NodeBackgroundColorSet_Handler,
		},
		{
			MethodName: "StatusInfoSet",
			Handler:    _Freeplane_StatusInfoSet_Handler,
		},
		{
			MethodName: "TextFSM",
			Handler:    _Freeplane_TextFSM_Handler,
		},
		{
			MethodName: "MindMapFromJSON",
			Handler:    _Freeplane_MindMapFromJSON_Handler,
		},
		{
			MethodName: "MindMapToJSON",
			Handler:    _Freeplane_MindMapToJSON_Handler,
		},
		{
			MethodName: "GetCurrentNode",
			Handler:    _Freeplane_GetCurrentNode_Handler,
		},
		{
			MethodName: "OpenMap",
			Handler:    _Freeplane_OpenMap_Handler,
		},
		{
			MethodName: "FocusNode",
			Handler:    _Freeplane_FocusNode_Handler,
		},
		{
			MethodName: "GetNodeText",
			Handler:    _Freeplane_GetNodeText_Handler,
		},
		{
			MethodName: "GetParentNode",
			Handler:    _Freeplane_GetParentNode_Handler,
		},
		{
			MethodName: "ListChildNodes",
			Handler:    _Freeplane_ListChildNodes_Handler,
		},
		{
			MethodName: "GetNodeNote",
			Handler:    _Freeplane_GetNodeNote_Handler,
		},
		{
			MethodName: "GetNodeLink",
			Handler:    _Freeplane_GetNodeLink_Handler,
		},
		{
			MethodName: "SetNodeText",
			Handler:    _Freeplane_SetNodeText_Handler,
		},
		{
			MethodName: "MoveNode",
			Handler:    _Freeplane_MoveNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "freeplane.proto",
}
