// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: freeplane.proto

#include "freeplane.pb.h"
#include "freeplane.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace freeplane {

static const char* Freeplane_method_names[] = {
  "/freeplane.Freeplane/CreateChild",
  "/freeplane.Freeplane/DeleteChild",
  "/freeplane.Freeplane/NodeAttributeAdd",
  "/freeplane.Freeplane/NodeLinkSet",
  "/freeplane.Freeplane/NodeDetailsSet",
  "/freeplane.Freeplane/NodeNoteSet",
  "/freeplane.Freeplane/NodeTagSet",
  "/freeplane.Freeplane/NodeTagAdd",
  "/freeplane.Freeplane/NodeConnect",
  "/freeplane.Freeplane/NodeAddIcon",
  "/freeplane.Freeplane/Groovy",
  "/freeplane.Freeplane/NodeColorSet",
  "/freeplane.Freeplane/NodeBackgroundColorSet",
  "/freeplane.Freeplane/StatusInfoSet",
  "/freeplane.Freeplane/TextFSM",
  "/freeplane.Freeplane/MindMapFromJSON",
  "/freeplane.Freeplane/MindMapToJSON",
  "/freeplane.Freeplane/GetCurrentNode",
  "/freeplane.Freeplane/OpenMap",
  "/freeplane.Freeplane/FocusNode",
  "/freeplane.Freeplane/GetNodeText",
  "/freeplane.Freeplane/GetParentNode",
  "/freeplane.Freeplane/ListChildNodes",
  "/freeplane.Freeplane/GetNodeNote",
  "/freeplane.Freeplane/GetNodeLink",
  "/freeplane.Freeplane/SetNodeText",
  "/freeplane.Freeplane/MoveNode",
};

std::unique_ptr< Freeplane::Stub> Freeplane::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Freeplane::Stub> stub(new Freeplane::Stub(channel, options));
  return stub;
}

Freeplane::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CreateChild_(Freeplane_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteChild_(Freeplane_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_NodeAttributeAdd_(Freeplane_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_NodeLinkSet_(Freeplane_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_NodeDetailsSet_(Freeplane_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_NodeNoteSet_(Freeplane_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_NodeTagSet_(Freeplane_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_NodeTagAdd_(Freeplane_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_NodeConnect_(Freeplane_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_NodeAddIcon_(Freeplane_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Groovy_(Freeplane_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_NodeColorSet_(Freeplane_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_NodeBackgroundColorSet_(Freeplane_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StatusInfoSet_(Freeplane_method_names[13], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_TextFSM_(Freeplane_method_names[14], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_MindMapFromJSON_(Freeplane_method_names[15], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_MindMapToJSON_(Freeplane_method_names[16], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetCurrentNode_(Freeplane_method_names[17], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_OpenMap_(Freeplane_method_names[18], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_FocusNode_(Freeplane_method_names[19], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetNodeText_(Freeplane_method_names[20], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetParentNode_(Freeplane_method_names[21], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListChildNodes_(Freeplane_method_names[22], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetNodeNote_(Freeplane_method_names[23], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetNodeLink_(Freeplane_method_names[24], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetNodeText_(Freeplane_method_names[25], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_MoveNode_(Freeplane_method_names[26], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Freeplane::Stub::CreateChild(::grpc::ClientContext* context, const ::freeplane::CreateChildRequest& request, ::freeplane::CreateChildResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::freeplane::CreateChildRequest, ::freeplane::CreateChildResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateChild_, context, request, response);
}

void Freeplane::Stub::async::CreateChild(::grpc::ClientContext* context, const ::freeplane::CreateChildRequest* request, ::freeplane::CreateChildResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::freeplane::CreateChildRequest, ::freeplane::CreateChildResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateChild_, context, request, response, std::move(f));
}

void Freeplane::Stub::async::CreateChild(::grpc::ClientContext* context, const ::freeplane::CreateChildRequest* request, ::freeplane::CreateChildResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateChild_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::freeplane::CreateChildResponse>* Freeplane::Stub::PrepareAsyncCreateChildRaw(::grpc::ClientContext* context, const ::freeplane::CreateChildRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::freeplane::CreateChildResponse, ::freeplane::CreateChildRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateChild_, context, request);
}

::grpc::ClientAsyncResponseReader< ::freeplane::CreateChildResponse>* Freeplane::Stub::AsyncCreateChildRaw(::grpc::ClientContext* context, const ::freeplane::CreateChildRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateChildRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Freeplane::Stub::DeleteChild(::grpc::ClientContext* context, const ::freeplane::DeleteChildRequest& request, ::freeplane::DeleteChildResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::freeplane::DeleteChildRequest, ::freeplane::DeleteChildResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteChild_, context, request, response);
}

void Freeplane::Stub::async::DeleteChild(::grpc::ClientContext* context, const ::freeplane::DeleteChildRequest* request, ::freeplane::DeleteChildResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::freeplane::DeleteChildRequest, ::freeplane::DeleteChildResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteChild_, context, request, response, std::move(f));
}

void Freeplane::Stub::async::DeleteChild(::grpc::ClientContext* context, const ::freeplane::DeleteChildRequest* request, ::freeplane::DeleteChildResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteChild_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::freeplane::DeleteChildResponse>* Freeplane::Stub::PrepareAsyncDeleteChildRaw(::grpc::ClientContext* context, const ::freeplane::DeleteChildRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::freeplane::DeleteChildResponse, ::freeplane::DeleteChildRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteChild_, context, request);
}

::grpc::ClientAsyncResponseReader< ::freeplane::DeleteChildResponse>* Freeplane::Stub::AsyncDeleteChildRaw(::grpc::ClientContext* context, const ::freeplane::DeleteChildRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteChildRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Freeplane::Stub::NodeAttributeAdd(::grpc::ClientContext* context, const ::freeplane::NodeAttributeAddRequest& request, ::freeplane::NodeAttributeAddResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::freeplane::NodeAttributeAddRequest, ::freeplane::NodeAttributeAddResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_NodeAttributeAdd_, context, request, response);
}

void Freeplane::Stub::async::NodeAttributeAdd(::grpc::ClientContext* context, const ::freeplane::NodeAttributeAddRequest* request, ::freeplane::NodeAttributeAddResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::freeplane::NodeAttributeAddRequest, ::freeplane::NodeAttributeAddResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NodeAttributeAdd_, context, request, response, std::move(f));
}

void Freeplane::Stub::async::NodeAttributeAdd(::grpc::ClientContext* context, const ::freeplane::NodeAttributeAddRequest* request, ::freeplane::NodeAttributeAddResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NodeAttributeAdd_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::freeplane::NodeAttributeAddResponse>* Freeplane::Stub::PrepareAsyncNodeAttributeAddRaw(::grpc::ClientContext* context, const ::freeplane::NodeAttributeAddRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::freeplane::NodeAttributeAddResponse, ::freeplane::NodeAttributeAddRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_NodeAttributeAdd_, context, request);
}

::grpc::ClientAsyncResponseReader< ::freeplane::NodeAttributeAddResponse>* Freeplane::Stub::AsyncNodeAttributeAddRaw(::grpc::ClientContext* context, const ::freeplane::NodeAttributeAddRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncNodeAttributeAddRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Freeplane::Stub::NodeLinkSet(::grpc::ClientContext* context, const ::freeplane::NodeLinkSetRequest& request, ::freeplane::NodeLinkSetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::freeplane::NodeLinkSetRequest, ::freeplane::NodeLinkSetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_NodeLinkSet_, context, request, response);
}

void Freeplane::Stub::async::NodeLinkSet(::grpc::ClientContext* context, const ::freeplane::NodeLinkSetRequest* request, ::freeplane::NodeLinkSetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::freeplane::NodeLinkSetRequest, ::freeplane::NodeLinkSetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NodeLinkSet_, context, request, response, std::move(f));
}

void Freeplane::Stub::async::NodeLinkSet(::grpc::ClientContext* context, const ::freeplane::NodeLinkSetRequest* request, ::freeplane::NodeLinkSetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NodeLinkSet_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::freeplane::NodeLinkSetResponse>* Freeplane::Stub::PrepareAsyncNodeLinkSetRaw(::grpc::ClientContext* context, const ::freeplane::NodeLinkSetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::freeplane::NodeLinkSetResponse, ::freeplane::NodeLinkSetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_NodeLinkSet_, context, request);
}

::grpc::ClientAsyncResponseReader< ::freeplane::NodeLinkSetResponse>* Freeplane::Stub::AsyncNodeLinkSetRaw(::grpc::ClientContext* context, const ::freeplane::NodeLinkSetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncNodeLinkSetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Freeplane::Stub::NodeDetailsSet(::grpc::ClientContext* context, const ::freeplane::NodeDetailsSetRequest& request, ::freeplane::NodeDetailsSetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::freeplane::NodeDetailsSetRequest, ::freeplane::NodeDetailsSetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_NodeDetailsSet_, context, request, response);
}

void Freeplane::Stub::async::NodeDetailsSet(::grpc::ClientContext* context, const ::freeplane::NodeDetailsSetRequest* request, ::freeplane::NodeDetailsSetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::freeplane::NodeDetailsSetRequest, ::freeplane::NodeDetailsSetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NodeDetailsSet_, context, request, response, std::move(f));
}

void Freeplane::Stub::async::NodeDetailsSet(::grpc::ClientContext* context, const ::freeplane::NodeDetailsSetRequest* request, ::freeplane::NodeDetailsSetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NodeDetailsSet_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::freeplane::NodeDetailsSetResponse>* Freeplane::Stub::PrepareAsyncNodeDetailsSetRaw(::grpc::ClientContext* context, const ::freeplane::NodeDetailsSetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::freeplane::NodeDetailsSetResponse, ::freeplane::NodeDetailsSetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_NodeDetailsSet_, context, request);
}

::grpc::ClientAsyncResponseReader< ::freeplane::NodeDetailsSetResponse>* Freeplane::Stub::AsyncNodeDetailsSetRaw(::grpc::ClientContext* context, const ::freeplane::NodeDetailsSetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncNodeDetailsSetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Freeplane::Stub::NodeNoteSet(::grpc::ClientContext* context, const ::freeplane::NodeNoteSetRequest& request, ::freeplane::NodeNoteSetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::freeplane::NodeNoteSetRequest, ::freeplane::NodeNoteSetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_NodeNoteSet_, context, request, response);
}

void Freeplane::Stub::async::NodeNoteSet(::grpc::ClientContext* context, const ::freeplane::NodeNoteSetRequest* request, ::freeplane::NodeNoteSetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::freeplane::NodeNoteSetRequest, ::freeplane::NodeNoteSetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NodeNoteSet_, context, request, response, std::move(f));
}

void Freeplane::Stub::async::NodeNoteSet(::grpc::ClientContext* context, const ::freeplane::NodeNoteSetRequest* request, ::freeplane::NodeNoteSetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NodeNoteSet_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::freeplane::NodeNoteSetResponse>* Freeplane::Stub::PrepareAsyncNodeNoteSetRaw(::grpc::ClientContext* context, const ::freeplane::NodeNoteSetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::freeplane::NodeNoteSetResponse, ::freeplane::NodeNoteSetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_NodeNoteSet_, context, request);
}

::grpc::ClientAsyncResponseReader< ::freeplane::NodeNoteSetResponse>* Freeplane::Stub::AsyncNodeNoteSetRaw(::grpc::ClientContext* context, const ::freeplane::NodeNoteSetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncNodeNoteSetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Freeplane::Stub::NodeTagSet(::grpc::ClientContext* context, const ::freeplane::NodeTagSetRequest& request, ::freeplane::NodeTagSetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::freeplane::NodeTagSetRequest, ::freeplane::NodeTagSetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_NodeTagSet_, context, request, response);
}

void Freeplane::Stub::async::NodeTagSet(::grpc::ClientContext* context, const ::freeplane::NodeTagSetRequest* request, ::freeplane::NodeTagSetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::freeplane::NodeTagSetRequest, ::freeplane::NodeTagSetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NodeTagSet_, context, request, response, std::move(f));
}

void Freeplane::Stub::async::NodeTagSet(::grpc::ClientContext* context, const ::freeplane::NodeTagSetRequest* request, ::freeplane::NodeTagSetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NodeTagSet_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::freeplane::NodeTagSetResponse>* Freeplane::Stub::PrepareAsyncNodeTagSetRaw(::grpc::ClientContext* context, const ::freeplane::NodeTagSetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::freeplane::NodeTagSetResponse, ::freeplane::NodeTagSetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_NodeTagSet_, context, request);
}

::grpc::ClientAsyncResponseReader< ::freeplane::NodeTagSetResponse>* Freeplane::Stub::AsyncNodeTagSetRaw(::grpc::ClientContext* context, const ::freeplane::NodeTagSetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncNodeTagSetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Freeplane::Stub::NodeTagAdd(::grpc::ClientContext* context, const ::freeplane::NodeTagAddRequest& request, ::freeplane::NodeTagAddResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::freeplane::NodeTagAddRequest, ::freeplane::NodeTagAddResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_NodeTagAdd_, context, request, response);
}

void Freeplane::Stub::async::NodeTagAdd(::grpc::ClientContext* context, const ::freeplane::NodeTagAddRequest* request, ::freeplane::NodeTagAddResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::freeplane::NodeTagAddRequest, ::freeplane::NodeTagAddResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NodeTagAdd_, context, request, response, std::move(f));
}

void Freeplane::Stub::async::NodeTagAdd(::grpc::ClientContext* context, const ::freeplane::NodeTagAddRequest* request, ::freeplane::NodeTagAddResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NodeTagAdd_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::freeplane::NodeTagAddResponse>* Freeplane::Stub::PrepareAsyncNodeTagAddRaw(::grpc::ClientContext* context, const ::freeplane::NodeTagAddRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::freeplane::NodeTagAddResponse, ::freeplane::NodeTagAddRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_NodeTagAdd_, context, request);
}

::grpc::ClientAsyncResponseReader< ::freeplane::NodeTagAddResponse>* Freeplane::Stub::AsyncNodeTagAddRaw(::grpc::ClientContext* context, const ::freeplane::NodeTagAddRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncNodeTagAddRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Freeplane::Stub::NodeConnect(::grpc::ClientContext* context, const ::freeplane::NodeConnectRequest& request, ::freeplane::NodeConnectResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::freeplane::NodeConnectRequest, ::freeplane::NodeConnectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_NodeConnect_, context, request, response);
}

void Freeplane::Stub::async::NodeConnect(::grpc::ClientContext* context, const ::freeplane::NodeConnectRequest* request, ::freeplane::NodeConnectResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::freeplane::NodeConnectRequest, ::freeplane::NodeConnectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NodeConnect_, context, request, response, std::move(f));
}

void Freeplane::Stub::async::NodeConnect(::grpc::ClientContext* context, const ::freeplane::NodeConnectRequest* request, ::freeplane::NodeConnectResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NodeConnect_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::freeplane::NodeConnectResponse>* Freeplane::Stub::PrepareAsyncNodeConnectRaw(::grpc::ClientContext* context, const ::freeplane::NodeConnectRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::freeplane::NodeConnectResponse, ::freeplane::NodeConnectRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_NodeConnect_, context, request);
}

::grpc::ClientAsyncResponseReader< ::freeplane::NodeConnectResponse>* Freeplane::Stub::AsyncNodeConnectRaw(::grpc::ClientContext* context, const ::freeplane::NodeConnectRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncNodeConnectRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Freeplane::Stub::NodeAddIcon(::grpc::ClientContext* context, const ::freeplane::NodeAddIconRequest& request, ::freeplane::NodeAddIconResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::freeplane::NodeAddIconRequest, ::freeplane::NodeAddIconResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_NodeAddIcon_, context, request, response);
}

void Freeplane::Stub::async::NodeAddIcon(::grpc::ClientContext* context, const ::freeplane::NodeAddIconRequest* request, ::freeplane::NodeAddIconResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::freeplane::NodeAddIconRequest, ::freeplane::NodeAddIconResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NodeAddIcon_, context, request, response, std::move(f));
}

void Freeplane::Stub::async::NodeAddIcon(::grpc::ClientContext* context, const ::freeplane::NodeAddIconRequest* request, ::freeplane::NodeAddIconResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NodeAddIcon_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::freeplane::NodeAddIconResponse>* Freeplane::Stub::PrepareAsyncNodeAddIconRaw(::grpc::ClientContext* context, const ::freeplane::NodeAddIconRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::freeplane::NodeAddIconResponse, ::freeplane::NodeAddIconRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_NodeAddIcon_, context, request);
}

::grpc::ClientAsyncResponseReader< ::freeplane::NodeAddIconResponse>* Freeplane::Stub::AsyncNodeAddIconRaw(::grpc::ClientContext* context, const ::freeplane::NodeAddIconRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncNodeAddIconRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Freeplane::Stub::Groovy(::grpc::ClientContext* context, const ::freeplane::GroovyRequest& request, ::freeplane::GroovyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::freeplane::GroovyRequest, ::freeplane::GroovyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Groovy_, context, request, response);
}

void Freeplane::Stub::async::Groovy(::grpc::ClientContext* context, const ::freeplane::GroovyRequest* request, ::freeplane::GroovyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::freeplane::GroovyRequest, ::freeplane::GroovyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Groovy_, context, request, response, std::move(f));
}

void Freeplane::Stub::async::Groovy(::grpc::ClientContext* context, const ::freeplane::GroovyRequest* request, ::freeplane::GroovyResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Groovy_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::freeplane::GroovyResponse>* Freeplane::Stub::PrepareAsyncGroovyRaw(::grpc::ClientContext* context, const ::freeplane::GroovyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::freeplane::GroovyResponse, ::freeplane::GroovyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Groovy_, context, request);
}

::grpc::ClientAsyncResponseReader< ::freeplane::GroovyResponse>* Freeplane::Stub::AsyncGroovyRaw(::grpc::ClientContext* context, const ::freeplane::GroovyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGroovyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Freeplane::Stub::NodeColorSet(::grpc::ClientContext* context, const ::freeplane::NodeColorSetRequest& request, ::freeplane::NodeColorSetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::freeplane::NodeColorSetRequest, ::freeplane::NodeColorSetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_NodeColorSet_, context, request, response);
}

void Freeplane::Stub::async::NodeColorSet(::grpc::ClientContext* context, const ::freeplane::NodeColorSetRequest* request, ::freeplane::NodeColorSetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::freeplane::NodeColorSetRequest, ::freeplane::NodeColorSetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NodeColorSet_, context, request, response, std::move(f));
}

void Freeplane::Stub::async::NodeColorSet(::grpc::ClientContext* context, const ::freeplane::NodeColorSetRequest* request, ::freeplane::NodeColorSetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NodeColorSet_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::freeplane::NodeColorSetResponse>* Freeplane::Stub::PrepareAsyncNodeColorSetRaw(::grpc::ClientContext* context, const ::freeplane::NodeColorSetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::freeplane::NodeColorSetResponse, ::freeplane::NodeColorSetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_NodeColorSet_, context, request);
}

::grpc::ClientAsyncResponseReader< ::freeplane::NodeColorSetResponse>* Freeplane::Stub::AsyncNodeColorSetRaw(::grpc::ClientContext* context, const ::freeplane::NodeColorSetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncNodeColorSetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Freeplane::Stub::NodeBackgroundColorSet(::grpc::ClientContext* context, const ::freeplane::NodeBackgroundColorSetRequest& request, ::freeplane::NodeBackgroundColorSetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::freeplane::NodeBackgroundColorSetRequest, ::freeplane::NodeBackgroundColorSetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_NodeBackgroundColorSet_, context, request, response);
}

void Freeplane::Stub::async::NodeBackgroundColorSet(::grpc::ClientContext* context, const ::freeplane::NodeBackgroundColorSetRequest* request, ::freeplane::NodeBackgroundColorSetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::freeplane::NodeBackgroundColorSetRequest, ::freeplane::NodeBackgroundColorSetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NodeBackgroundColorSet_, context, request, response, std::move(f));
}

void Freeplane::Stub::async::NodeBackgroundColorSet(::grpc::ClientContext* context, const ::freeplane::NodeBackgroundColorSetRequest* request, ::freeplane::NodeBackgroundColorSetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NodeBackgroundColorSet_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::freeplane::NodeBackgroundColorSetResponse>* Freeplane::Stub::PrepareAsyncNodeBackgroundColorSetRaw(::grpc::ClientContext* context, const ::freeplane::NodeBackgroundColorSetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::freeplane::NodeBackgroundColorSetResponse, ::freeplane::NodeBackgroundColorSetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_NodeBackgroundColorSet_, context, request);
}

::grpc::ClientAsyncResponseReader< ::freeplane::NodeBackgroundColorSetResponse>* Freeplane::Stub::AsyncNodeBackgroundColorSetRaw(::grpc::ClientContext* context, const ::freeplane::NodeBackgroundColorSetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncNodeBackgroundColorSetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Freeplane::Stub::StatusInfoSet(::grpc::ClientContext* context, const ::freeplane::StatusInfoSetRequest& request, ::freeplane::StatusInfoSetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::freeplane::StatusInfoSetRequest, ::freeplane::StatusInfoSetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StatusInfoSet_, context, request, response);
}

void Freeplane::Stub::async::StatusInfoSet(::grpc::ClientContext* context, const ::freeplane::StatusInfoSetRequest* request, ::freeplane::StatusInfoSetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::freeplane::StatusInfoSetRequest, ::freeplane::StatusInfoSetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StatusInfoSet_, context, request, response, std::move(f));
}

void Freeplane::Stub::async::StatusInfoSet(::grpc::ClientContext* context, const ::freeplane::StatusInfoSetRequest* request, ::freeplane::StatusInfoSetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StatusInfoSet_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::freeplane::StatusInfoSetResponse>* Freeplane::Stub::PrepareAsyncStatusInfoSetRaw(::grpc::ClientContext* context, const ::freeplane::StatusInfoSetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::freeplane::StatusInfoSetResponse, ::freeplane::StatusInfoSetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StatusInfoSet_, context, request);
}

::grpc::ClientAsyncResponseReader< ::freeplane::StatusInfoSetResponse>* Freeplane::Stub::AsyncStatusInfoSetRaw(::grpc::ClientContext* context, const ::freeplane::StatusInfoSetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStatusInfoSetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Freeplane::Stub::TextFSM(::grpc::ClientContext* context, const ::freeplane::TextFSMRequest& request, ::freeplane::TextFSMResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::freeplane::TextFSMRequest, ::freeplane::TextFSMResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_TextFSM_, context, request, response);
}

void Freeplane::Stub::async::TextFSM(::grpc::ClientContext* context, const ::freeplane::TextFSMRequest* request, ::freeplane::TextFSMResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::freeplane::TextFSMRequest, ::freeplane::TextFSMResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_TextFSM_, context, request, response, std::move(f));
}

void Freeplane::Stub::async::TextFSM(::grpc::ClientContext* context, const ::freeplane::TextFSMRequest* request, ::freeplane::TextFSMResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_TextFSM_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::freeplane::TextFSMResponse>* Freeplane::Stub::PrepareAsyncTextFSMRaw(::grpc::ClientContext* context, const ::freeplane::TextFSMRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::freeplane::TextFSMResponse, ::freeplane::TextFSMRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_TextFSM_, context, request);
}

::grpc::ClientAsyncResponseReader< ::freeplane::TextFSMResponse>* Freeplane::Stub::AsyncTextFSMRaw(::grpc::ClientContext* context, const ::freeplane::TextFSMRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncTextFSMRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Freeplane::Stub::MindMapFromJSON(::grpc::ClientContext* context, const ::freeplane::MindMapFromJSONRequest& request, ::freeplane::MindMapFromJSONResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::freeplane::MindMapFromJSONRequest, ::freeplane::MindMapFromJSONResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_MindMapFromJSON_, context, request, response);
}

void Freeplane::Stub::async::MindMapFromJSON(::grpc::ClientContext* context, const ::freeplane::MindMapFromJSONRequest* request, ::freeplane::MindMapFromJSONResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::freeplane::MindMapFromJSONRequest, ::freeplane::MindMapFromJSONResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MindMapFromJSON_, context, request, response, std::move(f));
}

void Freeplane::Stub::async::MindMapFromJSON(::grpc::ClientContext* context, const ::freeplane::MindMapFromJSONRequest* request, ::freeplane::MindMapFromJSONResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MindMapFromJSON_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::freeplane::MindMapFromJSONResponse>* Freeplane::Stub::PrepareAsyncMindMapFromJSONRaw(::grpc::ClientContext* context, const ::freeplane::MindMapFromJSONRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::freeplane::MindMapFromJSONResponse, ::freeplane::MindMapFromJSONRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_MindMapFromJSON_, context, request);
}

::grpc::ClientAsyncResponseReader< ::freeplane::MindMapFromJSONResponse>* Freeplane::Stub::AsyncMindMapFromJSONRaw(::grpc::ClientContext* context, const ::freeplane::MindMapFromJSONRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncMindMapFromJSONRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Freeplane::Stub::MindMapToJSON(::grpc::ClientContext* context, const ::freeplane::MindMapToJSONRequest& request, ::freeplane::MindMapToJSONResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::freeplane::MindMapToJSONRequest, ::freeplane::MindMapToJSONResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_MindMapToJSON_, context, request, response);
}

void Freeplane::Stub::async::MindMapToJSON(::grpc::ClientContext* context, const ::freeplane::MindMapToJSONRequest* request, ::freeplane::MindMapToJSONResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::freeplane::MindMapToJSONRequest, ::freeplane::MindMapToJSONResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MindMapToJSON_, context, request, response, std::move(f));
}

void Freeplane::Stub::async::MindMapToJSON(::grpc::ClientContext* context, const ::freeplane::MindMapToJSONRequest* request, ::freeplane::MindMapToJSONResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MindMapToJSON_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::freeplane::MindMapToJSONResponse>* Freeplane::Stub::PrepareAsyncMindMapToJSONRaw(::grpc::ClientContext* context, const ::freeplane::MindMapToJSONRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::freeplane::MindMapToJSONResponse, ::freeplane::MindMapToJSONRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_MindMapToJSON_, context, request);
}

::grpc::ClientAsyncResponseReader< ::freeplane::MindMapToJSONResponse>* Freeplane::Stub::AsyncMindMapToJSONRaw(::grpc::ClientContext* context, const ::freeplane::MindMapToJSONRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncMindMapToJSONRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Freeplane::Stub::GetCurrentNode(::grpc::ClientContext* context, const ::freeplane::GetCurrentNodeRequest& request, ::freeplane::GetCurrentNodeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::freeplane::GetCurrentNodeRequest, ::freeplane::GetCurrentNodeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetCurrentNode_, context, request, response);
}

void Freeplane::Stub::async::GetCurrentNode(::grpc::ClientContext* context, const ::freeplane::GetCurrentNodeRequest* request, ::freeplane::GetCurrentNodeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::freeplane::GetCurrentNodeRequest, ::freeplane::GetCurrentNodeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetCurrentNode_, context, request, response, std::move(f));
}

void Freeplane::Stub::async::GetCurrentNode(::grpc::ClientContext* context, const ::freeplane::GetCurrentNodeRequest* request, ::freeplane::GetCurrentNodeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetCurrentNode_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::freeplane::GetCurrentNodeResponse>* Freeplane::Stub::PrepareAsyncGetCurrentNodeRaw(::grpc::ClientContext* context, const ::freeplane::GetCurrentNodeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::freeplane::GetCurrentNodeResponse, ::freeplane::GetCurrentNodeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetCurrentNode_, context, request);
}

::grpc::ClientAsyncResponseReader< ::freeplane::GetCurrentNodeResponse>* Freeplane::Stub::AsyncGetCurrentNodeRaw(::grpc::ClientContext* context, const ::freeplane::GetCurrentNodeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetCurrentNodeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Freeplane::Stub::OpenMap(::grpc::ClientContext* context, const ::freeplane::OpenMapRequest& request, ::freeplane::OpenMapResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::freeplane::OpenMapRequest, ::freeplane::OpenMapResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_OpenMap_, context, request, response);
}

void Freeplane::Stub::async::OpenMap(::grpc::ClientContext* context, const ::freeplane::OpenMapRequest* request, ::freeplane::OpenMapResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::freeplane::OpenMapRequest, ::freeplane::OpenMapResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_OpenMap_, context, request, response, std::move(f));
}

void Freeplane::Stub::async::OpenMap(::grpc::ClientContext* context, const ::freeplane::OpenMapRequest* request, ::freeplane::OpenMapResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_OpenMap_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::freeplane::OpenMapResponse>* Freeplane::Stub::PrepareAsyncOpenMapRaw(::grpc::ClientContext* context, const ::freeplane::OpenMapRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::freeplane::OpenMapResponse, ::freeplane::OpenMapRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_OpenMap_, context, request);
}

::grpc::ClientAsyncResponseReader< ::freeplane::OpenMapResponse>* Freeplane::Stub::AsyncOpenMapRaw(::grpc::ClientContext* context, const ::freeplane::OpenMapRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncOpenMapRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Freeplane::Stub::FocusNode(::grpc::ClientContext* context, const ::freeplane::FocusNodeRequest& request, ::freeplane::FocusNodeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::freeplane::FocusNodeRequest, ::freeplane::FocusNodeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_FocusNode_, context, request, response);
}

void Freeplane::Stub::async::FocusNode(::grpc::ClientContext* context, const ::freeplane::FocusNodeRequest* request, ::freeplane::FocusNodeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::freeplane::FocusNodeRequest, ::freeplane::FocusNodeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FocusNode_, context, request, response, std::move(f));
}

void Freeplane::Stub::async::FocusNode(::grpc::ClientContext* context, const ::freeplane::FocusNodeRequest* request, ::freeplane::FocusNodeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FocusNode_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::freeplane::FocusNodeResponse>* Freeplane::Stub::PrepareAsyncFocusNodeRaw(::grpc::ClientContext* context, const ::freeplane::FocusNodeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::freeplane::FocusNodeResponse, ::freeplane::FocusNodeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_FocusNode_, context, request);
}

::grpc::ClientAsyncResponseReader< ::freeplane::FocusNodeResponse>* Freeplane::Stub::AsyncFocusNodeRaw(::grpc::ClientContext* context, const ::freeplane::FocusNodeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncFocusNodeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Freeplane::Stub::GetNodeText(::grpc::ClientContext* context, const ::freeplane::GetNodeTextRequest& request, ::freeplane::GetNodeTextResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::freeplane::GetNodeTextRequest, ::freeplane::GetNodeTextResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetNodeText_, context, request, response);
}

void Freeplane::Stub::async::GetNodeText(::grpc::ClientContext* context, const ::freeplane::GetNodeTextRequest* request, ::freeplane::GetNodeTextResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::freeplane::GetNodeTextRequest, ::freeplane::GetNodeTextResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetNodeText_, context, request, response, std::move(f));
}

void Freeplane::Stub::async::GetNodeText(::grpc::ClientContext* context, const ::freeplane::GetNodeTextRequest* request, ::freeplane::GetNodeTextResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetNodeText_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::freeplane::GetNodeTextResponse>* Freeplane::Stub::PrepareAsyncGetNodeTextRaw(::grpc::ClientContext* context, const ::freeplane::GetNodeTextRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::freeplane::GetNodeTextResponse, ::freeplane::GetNodeTextRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetNodeText_, context, request);
}

::grpc::ClientAsyncResponseReader< ::freeplane::GetNodeTextResponse>* Freeplane::Stub::AsyncGetNodeTextRaw(::grpc::ClientContext* context, const ::freeplane::GetNodeTextRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetNodeTextRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Freeplane::Stub::GetParentNode(::grpc::ClientContext* context, const ::freeplane::GetParentNodeRequest& request, ::freeplane::GetParentNodeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::freeplane::GetParentNodeRequest, ::freeplane::GetParentNodeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetParentNode_, context, request, response);
}

void Freeplane::Stub::async::GetParentNode(::grpc::ClientContext* context, const ::freeplane::GetParentNodeRequest* request, ::freeplane::GetParentNodeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::freeplane::GetParentNodeRequest, ::freeplane::GetParentNodeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetParentNode_, context, request, response, std::move(f));
}

void Freeplane::Stub::async::GetParentNode(::grpc::ClientContext* context, const ::freeplane::GetParentNodeRequest* request, ::freeplane::GetParentNodeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetParentNode_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::freeplane::GetParentNodeResponse>* Freeplane::Stub::PrepareAsyncGetParentNodeRaw(::grpc::ClientContext* context, const ::freeplane::GetParentNodeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::freeplane::GetParentNodeResponse, ::freeplane::GetParentNodeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetParentNode_, context, request);
}

::grpc::ClientAsyncResponseReader< ::freeplane::GetParentNodeResponse>* Freeplane::Stub::AsyncGetParentNodeRaw(::grpc::ClientContext* context, const ::freeplane::GetParentNodeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetParentNodeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Freeplane::Stub::ListChildNodes(::grpc::ClientContext* context, const ::freeplane::ListChildNodesRequest& request, ::freeplane::ListChildNodesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::freeplane::ListChildNodesRequest, ::freeplane::ListChildNodesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListChildNodes_, context, request, response);
}

void Freeplane::Stub::async::ListChildNodes(::grpc::ClientContext* context, const ::freeplane::ListChildNodesRequest* request, ::freeplane::ListChildNodesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::freeplane::ListChildNodesRequest, ::freeplane::ListChildNodesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListChildNodes_, context, request, response, std::move(f));
}

void Freeplane::Stub::async::ListChildNodes(::grpc::ClientContext* context, const ::freeplane::ListChildNodesRequest* request, ::freeplane::ListChildNodesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListChildNodes_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::freeplane::ListChildNodesResponse>* Freeplane::Stub::PrepareAsyncListChildNodesRaw(::grpc::ClientContext* context, const ::freeplane::ListChildNodesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::freeplane::ListChildNodesResponse, ::freeplane::ListChildNodesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListChildNodes_, context, request);
}

::grpc::ClientAsyncResponseReader< ::freeplane::ListChildNodesResponse>* Freeplane::Stub::AsyncListChildNodesRaw(::grpc::ClientContext* context, const ::freeplane::ListChildNodesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListChildNodesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Freeplane::Stub::GetNodeNote(::grpc::ClientContext* context, const ::freeplane::GetNodeNoteRequest& request, ::freeplane::GetNodeNoteResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::freeplane::GetNodeNoteRequest, ::freeplane::GetNodeNoteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetNodeNote_, context, request, response);
}

void Freeplane::Stub::async::GetNodeNote(::grpc::ClientContext* context, const ::freeplane::GetNodeNoteRequest* request, ::freeplane::GetNodeNoteResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::freeplane::GetNodeNoteRequest, ::freeplane::GetNodeNoteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetNodeNote_, context, request, response, std::move(f));
}

void Freeplane::Stub::async::GetNodeNote(::grpc::ClientContext* context, const ::freeplane::GetNodeNoteRequest* request, ::freeplane::GetNodeNoteResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetNodeNote_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::freeplane::GetNodeNoteResponse>* Freeplane::Stub::PrepareAsyncGetNodeNoteRaw(::grpc::ClientContext* context, const ::freeplane::GetNodeNoteRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::freeplane::GetNodeNoteResponse, ::freeplane::GetNodeNoteRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetNodeNote_, context, request);
}

::grpc::ClientAsyncResponseReader< ::freeplane::GetNodeNoteResponse>* Freeplane::Stub::AsyncGetNodeNoteRaw(::grpc::ClientContext* context, const ::freeplane::GetNodeNoteRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetNodeNoteRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Freeplane::Stub::GetNodeLink(::grpc::ClientContext* context, const ::freeplane::GetNodeLinkRequest& request, ::freeplane::GetNodeLinkResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::freeplane::GetNodeLinkRequest, ::freeplane::GetNodeLinkResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetNodeLink_, context, request, response);
}

void Freeplane::Stub::async::GetNodeLink(::grpc::ClientContext* context, const ::freeplane::GetNodeLinkRequest* request, ::freeplane::GetNodeLinkResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::freeplane::GetNodeLinkRequest, ::freeplane::GetNodeLinkResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetNodeLink_, context, request, response, std::move(f));
}

void Freeplane::Stub::async::GetNodeLink(::grpc::ClientContext* context, const ::freeplane::GetNodeLinkRequest* request, ::freeplane::GetNodeLinkResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetNodeLink_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::freeplane::GetNodeLinkResponse>* Freeplane::Stub::PrepareAsyncGetNodeLinkRaw(::grpc::ClientContext* context, const ::freeplane::GetNodeLinkRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::freeplane::GetNodeLinkResponse, ::freeplane::GetNodeLinkRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetNodeLink_, context, request);
}

::grpc::ClientAsyncResponseReader< ::freeplane::GetNodeLinkResponse>* Freeplane::Stub::AsyncGetNodeLinkRaw(::grpc::ClientContext* context, const ::freeplane::GetNodeLinkRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetNodeLinkRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Freeplane::Stub::SetNodeText(::grpc::ClientContext* context, const ::freeplane::SetNodeTextRequest& request, ::freeplane::SetNodeTextResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::freeplane::SetNodeTextRequest, ::freeplane::SetNodeTextResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetNodeText_, context, request, response);
}

void Freeplane::Stub::async::SetNodeText(::grpc::ClientContext* context, const ::freeplane::SetNodeTextRequest* request, ::freeplane::SetNodeTextResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::freeplane::SetNodeTextRequest, ::freeplane::SetNodeTextResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetNodeText_, context, request, response, std::move(f));
}

void Freeplane::Stub::async::SetNodeText(::grpc::ClientContext* context, const ::freeplane::SetNodeTextRequest* request, ::freeplane::SetNodeTextResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetNodeText_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::freeplane::SetNodeTextResponse>* Freeplane::Stub::PrepareAsyncSetNodeTextRaw(::grpc::ClientContext* context, const ::freeplane::SetNodeTextRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::freeplane::SetNodeTextResponse, ::freeplane::SetNodeTextRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetNodeText_, context, request);
}

::grpc::ClientAsyncResponseReader< ::freeplane::SetNodeTextResponse>* Freeplane::Stub::AsyncSetNodeTextRaw(::grpc::ClientContext* context, const ::freeplane::SetNodeTextRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetNodeTextRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Freeplane::Stub::MoveNode(::grpc::ClientContext* context, const ::freeplane::MoveNodeRequest& request, ::freeplane::MoveNodeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::freeplane::MoveNodeRequest, ::freeplane::MoveNodeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_MoveNode_, context, request, response);
}

void Freeplane::Stub::async::MoveNode(::grpc::ClientContext* context, const ::freeplane::MoveNodeRequest* request, ::freeplane::MoveNodeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::freeplane::MoveNodeRequest, ::freeplane::MoveNodeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MoveNode_, context, request, response, std::move(f));
}

void Freeplane::Stub::async::MoveNode(::grpc::ClientContext* context, const ::freeplane::MoveNodeRequest* request, ::freeplane::MoveNodeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MoveNode_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::freeplane::MoveNodeResponse>* Freeplane::Stub::PrepareAsyncMoveNodeRaw(::grpc::ClientContext* context, const ::freeplane::MoveNodeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::freeplane::MoveNodeResponse, ::freeplane::MoveNodeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_MoveNode_, context, request);
}

::grpc::ClientAsyncResponseReader< ::freeplane::MoveNodeResponse>* Freeplane::Stub::AsyncMoveNodeRaw(::grpc::ClientContext* context, const ::freeplane::MoveNodeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncMoveNodeRaw(context, request, cq);
  result->StartCall();
  return result;
}

Freeplane::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Freeplane_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Freeplane::Service, ::freeplane::CreateChildRequest, ::freeplane::CreateChildResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Freeplane::Service* service,
             ::grpc::ServerContext* ctx,
             const ::freeplane::CreateChildRequest* req,
             ::freeplane::CreateChildResponse* resp) {
               return service->CreateChild(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Freeplane_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Freeplane::Service, ::freeplane::DeleteChildRequest, ::freeplane::DeleteChildResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Freeplane::Service* service,
             ::grpc::ServerContext* ctx,
             const ::freeplane::DeleteChildRequest* req,
             ::freeplane::DeleteChildResponse* resp) {
               return service->DeleteChild(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Freeplane_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Freeplane::Service, ::freeplane::NodeAttributeAddRequest, ::freeplane::NodeAttributeAddResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Freeplane::Service* service,
             ::grpc::ServerContext* ctx,
             const ::freeplane::NodeAttributeAddRequest* req,
             ::freeplane::NodeAttributeAddResponse* resp) {
               return service->NodeAttributeAdd(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Freeplane_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Freeplane::Service, ::freeplane::NodeLinkSetRequest, ::freeplane::NodeLinkSetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Freeplane::Service* service,
             ::grpc::ServerContext* ctx,
             const ::freeplane::NodeLinkSetRequest* req,
             ::freeplane::NodeLinkSetResponse* resp) {
               return service->NodeLinkSet(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Freeplane_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Freeplane::Service, ::freeplane::NodeDetailsSetRequest, ::freeplane::NodeDetailsSetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Freeplane::Service* service,
             ::grpc::ServerContext* ctx,
             const ::freeplane::NodeDetailsSetRequest* req,
             ::freeplane::NodeDetailsSetResponse* resp) {
               return service->NodeDetailsSet(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Freeplane_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Freeplane::Service, ::freeplane::NodeNoteSetRequest, ::freeplane::NodeNoteSetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Freeplane::Service* service,
             ::grpc::ServerContext* ctx,
             const ::freeplane::NodeNoteSetRequest* req,
             ::freeplane::NodeNoteSetResponse* resp) {
               return service->NodeNoteSet(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Freeplane_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Freeplane::Service, ::freeplane::NodeTagSetRequest, ::freeplane::NodeTagSetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Freeplane::Service* service,
             ::grpc::ServerContext* ctx,
             const ::freeplane::NodeTagSetRequest* req,
             ::freeplane::NodeTagSetResponse* resp) {
               return service->NodeTagSet(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Freeplane_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Freeplane::Service, ::freeplane::NodeTagAddRequest, ::freeplane::NodeTagAddResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Freeplane::Service* service,
             ::grpc::ServerContext* ctx,
             const ::freeplane::NodeTagAddRequest* req,
             ::freeplane::NodeTagAddResponse* resp) {
               return service->NodeTagAdd(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Freeplane_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Freeplane::Service, ::freeplane::NodeConnectRequest, ::freeplane::NodeConnectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Freeplane::Service* service,
             ::grpc::ServerContext* ctx,
             const ::freeplane::NodeConnectRequest* req,
             ::freeplane::NodeConnectResponse* resp) {
               return service->NodeConnect(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Freeplane_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Freeplane::Service, ::freeplane::NodeAddIconRequest, ::freeplane::NodeAddIconResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Freeplane::Service* service,
             ::grpc::ServerContext* ctx,
             const ::freeplane::NodeAddIconRequest* req,
             ::freeplane::NodeAddIconResponse* resp) {
               return service->NodeAddIcon(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Freeplane_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Freeplane::Service, ::freeplane::GroovyRequest, ::freeplane::GroovyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Freeplane::Service* service,
             ::grpc::ServerContext* ctx,
             const ::freeplane::GroovyRequest* req,
             ::freeplane::GroovyResponse* resp) {
               return service->Groovy(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Freeplane_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Freeplane::Service, ::freeplane::NodeColorSetRequest, ::freeplane::NodeColorSetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Freeplane::Service* service,
             ::grpc::ServerContext* ctx,
             const ::freeplane::NodeColorSetRequest* req,
             ::freeplane::NodeColorSetResponse* resp) {
               return service->NodeColorSet(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Freeplane_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Freeplane::Service, ::freeplane::NodeBackgroundColorSetRequest, ::freeplane::NodeBackgroundColorSetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Freeplane::Service* service,
             ::grpc::ServerContext* ctx,
             const ::freeplane::NodeBackgroundColorSetRequest* req,
             ::freeplane::NodeBackgroundColorSetResponse* resp) {
               return service->NodeBackgroundColorSet(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Freeplane_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Freeplane::Service, ::freeplane::StatusInfoSetRequest, ::freeplane::StatusInfoSetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Freeplane::Service* service,
             ::grpc::ServerContext* ctx,
             const ::freeplane::StatusInfoSetRequest* req,
             ::freeplane::StatusInfoSetResponse* resp) {
               return service->StatusInfoSet(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Freeplane_method_names[14],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Freeplane::Service, ::freeplane::TextFSMRequest, ::freeplane::TextFSMResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Freeplane::Service* service,
             ::grpc::ServerContext* ctx,
             const ::freeplane::TextFSMRequest* req,
             ::freeplane::TextFSMResponse* resp) {
               return service->TextFSM(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Freeplane_method_names[15],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Freeplane::Service, ::freeplane::MindMapFromJSONRequest, ::freeplane::MindMapFromJSONResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Freeplane::Service* service,
             ::grpc::ServerContext* ctx,
             const ::freeplane::MindMapFromJSONRequest* req,
             ::freeplane::MindMapFromJSONResponse* resp) {
               return service->MindMapFromJSON(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Freeplane_method_names[16],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Freeplane::Service, ::freeplane::MindMapToJSONRequest, ::freeplane::MindMapToJSONResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Freeplane::Service* service,
             ::grpc::ServerContext* ctx,
             const ::freeplane::MindMapToJSONRequest* req,
             ::freeplane::MindMapToJSONResponse* resp) {
               return service->MindMapToJSON(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Freeplane_method_names[17],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Freeplane::Service, ::freeplane::GetCurrentNodeRequest, ::freeplane::GetCurrentNodeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Freeplane::Service* service,
             ::grpc::ServerContext* ctx,
             const ::freeplane::GetCurrentNodeRequest* req,
             ::freeplane::GetCurrentNodeResponse* resp) {
               return service->GetCurrentNode(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Freeplane_method_names[18],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Freeplane::Service, ::freeplane::OpenMapRequest, ::freeplane::OpenMapResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Freeplane::Service* service,
             ::grpc::ServerContext* ctx,
             const ::freeplane::OpenMapRequest* req,
             ::freeplane::OpenMapResponse* resp) {
               return service->OpenMap(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Freeplane_method_names[19],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Freeplane::Service, ::freeplane::FocusNodeRequest, ::freeplane::FocusNodeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Freeplane::Service* service,
             ::grpc::ServerContext* ctx,
             const ::freeplane::FocusNodeRequest* req,
             ::freeplane::FocusNodeResponse* resp) {
               return service->FocusNode(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Freeplane_method_names[20],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Freeplane::Service, ::freeplane::GetNodeTextRequest, ::freeplane::GetNodeTextResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Freeplane::Service* service,
             ::grpc::ServerContext* ctx,
             const ::freeplane::GetNodeTextRequest* req,
             ::freeplane::GetNodeTextResponse* resp) {
               return service->GetNodeText(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Freeplane_method_names[21],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Freeplane::Service, ::freeplane::GetParentNodeRequest, ::freeplane::GetParentNodeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Freeplane::Service* service,
             ::grpc::ServerContext* ctx,
             const ::freeplane::GetParentNodeRequest* req,
             ::freeplane::GetParentNodeResponse* resp) {
               return service->GetParentNode(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Freeplane_method_names[22],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Freeplane::Service, ::freeplane::ListChildNodesRequest, ::freeplane::ListChildNodesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Freeplane::Service* service,
             ::grpc::ServerContext* ctx,
             const ::freeplane::ListChildNodesRequest* req,
             ::freeplane::ListChildNodesResponse* resp) {
               return service->ListChildNodes(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Freeplane_method_names[23],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Freeplane::Service, ::freeplane::GetNodeNoteRequest, ::freeplane::GetNodeNoteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Freeplane::Service* service,
             ::grpc::ServerContext* ctx,
             const ::freeplane::GetNodeNoteRequest* req,
             ::freeplane::GetNodeNoteResponse* resp) {
               return service->GetNodeNote(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Freeplane_method_names[24],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Freeplane::Service, ::freeplane::GetNodeLinkRequest, ::freeplane::GetNodeLinkResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Freeplane::Service* service,
             ::grpc::ServerContext* ctx,
             const ::freeplane::GetNodeLinkRequest* req,
             ::freeplane::GetNodeLinkResponse* resp) {
               return service->GetNodeLink(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Freeplane_method_names[25],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Freeplane::Service, ::freeplane::SetNodeTextRequest, ::freeplane::SetNodeTextResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Freeplane::Service* service,
             ::grpc::ServerContext* ctx,
             const ::freeplane::SetNodeTextRequest* req,
             ::freeplane::SetNodeTextResponse* resp) {
               return service->SetNodeText(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Freeplane_method_names[26],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Freeplane::Service, ::freeplane::MoveNodeRequest, ::freeplane::MoveNodeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Freeplane::Service* service,
             ::grpc::ServerContext* ctx,
             const ::freeplane::MoveNodeRequest* req,
             ::freeplane::MoveNodeResponse* resp) {
               return service->MoveNode(ctx, req, resp);
             }, this)));
}

Freeplane::Service::~Service() {
}

::grpc::Status Freeplane::Service::CreateChild(::grpc::ServerContext* context, const ::freeplane::CreateChildRequest* request, ::freeplane::CreateChildResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Freeplane::Service::DeleteChild(::grpc::ServerContext* context, const ::freeplane::DeleteChildRequest* request, ::freeplane::DeleteChildResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Freeplane::Service::NodeAttributeAdd(::grpc::ServerContext* context, const ::freeplane::NodeAttributeAddRequest* request, ::freeplane::NodeAttributeAddResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Freeplane::Service::NodeLinkSet(::grpc::ServerContext* context, const ::freeplane::NodeLinkSetRequest* request, ::freeplane::NodeLinkSetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Freeplane::Service::NodeDetailsSet(::grpc::ServerContext* context, const ::freeplane::NodeDetailsSetRequest* request, ::freeplane::NodeDetailsSetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Freeplane::Service::NodeNoteSet(::grpc::ServerContext* context, const ::freeplane::NodeNoteSetRequest* request, ::freeplane::NodeNoteSetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Freeplane::Service::NodeTagSet(::grpc::ServerContext* context, const ::freeplane::NodeTagSetRequest* request, ::freeplane::NodeTagSetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Freeplane::Service::NodeTagAdd(::grpc::ServerContext* context, const ::freeplane::NodeTagAddRequest* request, ::freeplane::NodeTagAddResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Freeplane::Service::NodeConnect(::grpc::ServerContext* context, const ::freeplane::NodeConnectRequest* request, ::freeplane::NodeConnectResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Freeplane::Service::NodeAddIcon(::grpc::ServerContext* context, const ::freeplane::NodeAddIconRequest* request, ::freeplane::NodeAddIconResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Freeplane::Service::Groovy(::grpc::ServerContext* context, const ::freeplane::GroovyRequest* request, ::freeplane::GroovyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Freeplane::Service::NodeColorSet(::grpc::ServerContext* context, const ::freeplane::NodeColorSetRequest* request, ::freeplane::NodeColorSetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Freeplane::Service::NodeBackgroundColorSet(::grpc::ServerContext* context, const ::freeplane::NodeBackgroundColorSetRequest* request, ::freeplane::NodeBackgroundColorSetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Freeplane::Service::StatusInfoSet(::grpc::ServerContext* context, const ::freeplane::StatusInfoSetRequest* request, ::freeplane::StatusInfoSetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Freeplane::Service::TextFSM(::grpc::ServerContext* context, const ::freeplane::TextFSMRequest* request, ::freeplane::TextFSMResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Freeplane::Service::MindMapFromJSON(::grpc::ServerContext* context, const ::freeplane::MindMapFromJSONRequest* request, ::freeplane::MindMapFromJSONResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Freeplane::Service::MindMapToJSON(::grpc::ServerContext* context, const ::freeplane::MindMapToJSONRequest* request, ::freeplane::MindMapToJSONResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Freeplane::Service::GetCurrentNode(::grpc::ServerContext* context, const ::freeplane::GetCurrentNodeRequest* request, ::freeplane::GetCurrentNodeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Freeplane::Service::OpenMap(::grpc::ServerContext* context, const ::freeplane::OpenMapRequest* request, ::freeplane::OpenMapResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Freeplane::Service::FocusNode(::grpc::ServerContext* context, const ::freeplane::FocusNodeRequest* request, ::freeplane::FocusNodeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Freeplane::Service::GetNodeText(::grpc::ServerContext* context, const ::freeplane::GetNodeTextRequest* request, ::freeplane::GetNodeTextResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Freeplane::Service::GetParentNode(::grpc::ServerContext* context, const ::freeplane::GetParentNodeRequest* request, ::freeplane::GetParentNodeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Freeplane::Service::ListChildNodes(::grpc::ServerContext* context, const ::freeplane::ListChildNodesRequest* request, ::freeplane::ListChildNodesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Freeplane::Service::GetNodeNote(::grpc::ServerContext* context, const ::freeplane::GetNodeNoteRequest* request, ::freeplane::GetNodeNoteResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Freeplane::Service::GetNodeLink(::grpc::ServerContext* context, const ::freeplane::GetNodeLinkRequest* request, ::freeplane::GetNodeLinkResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Freeplane::Service::SetNodeText(::grpc::ServerContext* context, const ::freeplane::SetNodeTextRequest* request, ::freeplane::SetNodeTextResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Freeplane::Service::MoveNode(::grpc::ServerContext* context, const ::freeplane::MoveNodeRequest* request, ::freeplane::MoveNodeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace freeplane

