// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/metacoma/freeplane_plugin_grpc/grpc/golang (interfaces: FreeplaneClientInterface)
//
// Generated by this command:
//
//	mockgen -package=mock -destination=internal/mock/mock_freeplane.go github.com/metacoma/freeplane_plugin_grpc/grpc/golang FreeplaneClientInterface
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	pb "github.com/metacoma/freeplane_plugin_grpc/grpc/golang/pb"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockFreeplaneClientInterface is a mock of FreeplaneClientInterface interface.
type MockFreeplaneClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockFreeplaneClientInterfaceMockRecorder
	isgomock struct{}
}

// MockFreeplaneClientInterfaceMockRecorder is the mock recorder for MockFreeplaneClientInterface.
type MockFreeplaneClientInterfaceMockRecorder struct {
	mock *MockFreeplaneClientInterface
}

// NewMockFreeplaneClientInterface creates a new mock instance.
func NewMockFreeplaneClientInterface(ctrl *gomock.Controller) *MockFreeplaneClientInterface {
	mock := &MockFreeplaneClientInterface{ctrl: ctrl}
	mock.recorder = &MockFreeplaneClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFreeplaneClientInterface) EXPECT() *MockFreeplaneClientInterfaceMockRecorder {
	return m.recorder
}

// CreateChild mocks base method.
func (m *MockFreeplaneClientInterface) CreateChild(ctx context.Context, in *pb.CreateChildRequest, opts ...grpc.CallOption) (*pb.CreateChildResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateChild", varargs...)
	ret0, _ := ret[0].(*pb.CreateChildResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChild indicates an expected call of CreateChild.
func (mr *MockFreeplaneClientInterfaceMockRecorder) CreateChild(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChild", reflect.TypeOf((*MockFreeplaneClientInterface)(nil).CreateChild), varargs...)
}

// DeleteChild mocks base method.
func (m *MockFreeplaneClientInterface) DeleteChild(ctx context.Context, in *pb.DeleteChildRequest, opts ...grpc.CallOption) (*pb.DeleteChildResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteChild", varargs...)
	ret0, _ := ret[0].(*pb.DeleteChildResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteChild indicates an expected call of DeleteChild.
func (mr *MockFreeplaneClientInterfaceMockRecorder) DeleteChild(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChild", reflect.TypeOf((*MockFreeplaneClientInterface)(nil).DeleteChild), varargs...)
}

// FocusNode mocks base method.
func (m *MockFreeplaneClientInterface) FocusNode(ctx context.Context, in *pb.FocusNodeRequest, opts ...grpc.CallOption) (*pb.FocusNodeResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FocusNode", varargs...)
	ret0, _ := ret[0].(*pb.FocusNodeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FocusNode indicates an expected call of FocusNode.
func (mr *MockFreeplaneClientInterfaceMockRecorder) FocusNode(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FocusNode", reflect.TypeOf((*MockFreeplaneClientInterface)(nil).FocusNode), varargs...)
}

// GetCurrentNode mocks base method.
func (m *MockFreeplaneClientInterface) GetCurrentNode(ctx context.Context, in *pb.GetCurrentNodeRequest, opts ...grpc.CallOption) (*pb.GetCurrentNodeResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCurrentNode", varargs...)
	ret0, _ := ret[0].(*pb.GetCurrentNodeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentNode indicates an expected call of GetCurrentNode.
func (mr *MockFreeplaneClientInterfaceMockRecorder) GetCurrentNode(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentNode", reflect.TypeOf((*MockFreeplaneClientInterface)(nil).GetCurrentNode), varargs...)
}

// GetNodeLink mocks base method.
func (m *MockFreeplaneClientInterface) GetNodeLink(ctx context.Context, in *pb.GetNodeLinkRequest, opts ...grpc.CallOption) (*pb.GetNodeLinkResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetNodeLink", varargs...)
	ret0, _ := ret[0].(*pb.GetNodeLinkResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodeLink indicates an expected call of GetNodeLink.
func (mr *MockFreeplaneClientInterfaceMockRecorder) GetNodeLink(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeLink", reflect.TypeOf((*MockFreeplaneClientInterface)(nil).GetNodeLink), varargs...)
}

// GetNodeNote mocks base method.
func (m *MockFreeplaneClientInterface) GetNodeNote(ctx context.Context, in *pb.GetNodeNoteRequest, opts ...grpc.CallOption) (*pb.GetNodeNoteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetNodeNote", varargs...)
	ret0, _ := ret[0].(*pb.GetNodeNoteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodeNote indicates an expected call of GetNodeNote.
func (mr *MockFreeplaneClientInterfaceMockRecorder) GetNodeNote(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeNote", reflect.TypeOf((*MockFreeplaneClientInterface)(nil).GetNodeNote), varargs...)
}

// GetNodeText mocks base method.
func (m *MockFreeplaneClientInterface) GetNodeText(ctx context.Context, in *pb.GetNodeTextRequest, opts ...grpc.CallOption) (*pb.GetNodeTextResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetNodeText", varargs...)
	ret0, _ := ret[0].(*pb.GetNodeTextResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodeText indicates an expected call of GetNodeText.
func (mr *MockFreeplaneClientInterfaceMockRecorder) GetNodeText(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeText", reflect.TypeOf((*MockFreeplaneClientInterface)(nil).GetNodeText), varargs...)
}

// GetParentNode mocks base method.
func (m *MockFreeplaneClientInterface) GetParentNode(ctx context.Context, in *pb.GetParentNodeRequest, opts ...grpc.CallOption) (*pb.GetParentNodeResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetParentNode", varargs...)
	ret0, _ := ret[0].(*pb.GetParentNodeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParentNode indicates an expected call of GetParentNode.
func (mr *MockFreeplaneClientInterfaceMockRecorder) GetParentNode(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParentNode", reflect.TypeOf((*MockFreeplaneClientInterface)(nil).GetParentNode), varargs...)
}

// Groovy mocks base method.
func (m *MockFreeplaneClientInterface) Groovy(ctx context.Context, in *pb.GroovyRequest, opts ...grpc.CallOption) (*pb.GroovyResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Groovy", varargs...)
	ret0, _ := ret[0].(*pb.GroovyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Groovy indicates an expected call of Groovy.
func (mr *MockFreeplaneClientInterfaceMockRecorder) Groovy(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Groovy", reflect.TypeOf((*MockFreeplaneClientInterface)(nil).Groovy), varargs...)
}

// ListChildNodes mocks base method.
func (m *MockFreeplaneClientInterface) ListChildNodes(ctx context.Context, in *pb.ListChildNodesRequest, opts ...grpc.CallOption) (*pb.ListChildNodesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListChildNodes", varargs...)
	ret0, _ := ret[0].(*pb.ListChildNodesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChildNodes indicates an expected call of ListChildNodes.
func (mr *MockFreeplaneClientInterfaceMockRecorder) ListChildNodes(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChildNodes", reflect.TypeOf((*MockFreeplaneClientInterface)(nil).ListChildNodes), varargs...)
}

// MindMapFromJSON mocks base method.
func (m *MockFreeplaneClientInterface) MindMapFromJSON(ctx context.Context, in *pb.MindMapFromJSONRequest, opts ...grpc.CallOption) (*pb.MindMapFromJSONResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MindMapFromJSON", varargs...)
	ret0, _ := ret[0].(*pb.MindMapFromJSONResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MindMapFromJSON indicates an expected call of MindMapFromJSON.
func (mr *MockFreeplaneClientInterfaceMockRecorder) MindMapFromJSON(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MindMapFromJSON", reflect.TypeOf((*MockFreeplaneClientInterface)(nil).MindMapFromJSON), varargs...)
}

// MindMapToJSON mocks base method.
func (m *MockFreeplaneClientInterface) MindMapToJSON(ctx context.Context, in *pb.MindMapToJSONRequest, opts ...grpc.CallOption) (*pb.MindMapToJSONResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MindMapToJSON", varargs...)
	ret0, _ := ret[0].(*pb.MindMapToJSONResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MindMapToJSON indicates an expected call of MindMapToJSON.
func (mr *MockFreeplaneClientInterfaceMockRecorder) MindMapToJSON(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MindMapToJSON", reflect.TypeOf((*MockFreeplaneClientInterface)(nil).MindMapToJSON), varargs...)
}

// MoveNode mocks base method.
func (m *MockFreeplaneClientInterface) MoveNode(ctx context.Context, in *pb.MoveNodeRequest, opts ...grpc.CallOption) (*pb.MoveNodeResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MoveNode", varargs...)
	ret0, _ := ret[0].(*pb.MoveNodeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveNode indicates an expected call of MoveNode.
func (mr *MockFreeplaneClientInterfaceMockRecorder) MoveNode(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveNode", reflect.TypeOf((*MockFreeplaneClientInterface)(nil).MoveNode), varargs...)
}

// NodeAddIcon mocks base method.
func (m *MockFreeplaneClientInterface) NodeAddIcon(ctx context.Context, in *pb.NodeAddIconRequest, opts ...grpc.CallOption) (*pb.NodeAddIconResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NodeAddIcon", varargs...)
	ret0, _ := ret[0].(*pb.NodeAddIconResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NodeAddIcon indicates an expected call of NodeAddIcon.
func (mr *MockFreeplaneClientInterfaceMockRecorder) NodeAddIcon(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NodeAddIcon", reflect.TypeOf((*MockFreeplaneClientInterface)(nil).NodeAddIcon), varargs...)
}

// NodeAttributeAdd mocks base method.
func (m *MockFreeplaneClientInterface) NodeAttributeAdd(ctx context.Context, in *pb.NodeAttributeAddRequest, opts ...grpc.CallOption) (*pb.NodeAttributeAddResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NodeAttributeAdd", varargs...)
	ret0, _ := ret[0].(*pb.NodeAttributeAddResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NodeAttributeAdd indicates an expected call of NodeAttributeAdd.
func (mr *MockFreeplaneClientInterfaceMockRecorder) NodeAttributeAdd(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NodeAttributeAdd", reflect.TypeOf((*MockFreeplaneClientInterface)(nil).NodeAttributeAdd), varargs...)
}

// NodeBackgroundColorSet mocks base method.
func (m *MockFreeplaneClientInterface) NodeBackgroundColorSet(ctx context.Context, in *pb.NodeBackgroundColorSetRequest, opts ...grpc.CallOption) (*pb.NodeBackgroundColorSetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NodeBackgroundColorSet", varargs...)
	ret0, _ := ret[0].(*pb.NodeBackgroundColorSetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NodeBackgroundColorSet indicates an expected call of NodeBackgroundColorSet.
func (mr *MockFreeplaneClientInterfaceMockRecorder) NodeBackgroundColorSet(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NodeBackgroundColorSet", reflect.TypeOf((*MockFreeplaneClientInterface)(nil).NodeBackgroundColorSet), varargs...)
}

// NodeColorSet mocks base method.
func (m *MockFreeplaneClientInterface) NodeColorSet(ctx context.Context, in *pb.NodeColorSetRequest, opts ...grpc.CallOption) (*pb.NodeColorSetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NodeColorSet", varargs...)
	ret0, _ := ret[0].(*pb.NodeColorSetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NodeColorSet indicates an expected call of NodeColorSet.
func (mr *MockFreeplaneClientInterfaceMockRecorder) NodeColorSet(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NodeColorSet", reflect.TypeOf((*MockFreeplaneClientInterface)(nil).NodeColorSet), varargs...)
}

// NodeConnect mocks base method.
func (m *MockFreeplaneClientInterface) NodeConnect(ctx context.Context, in *pb.NodeConnectRequest, opts ...grpc.CallOption) (*pb.NodeConnectResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NodeConnect", varargs...)
	ret0, _ := ret[0].(*pb.NodeConnectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NodeConnect indicates an expected call of NodeConnect.
func (mr *MockFreeplaneClientInterfaceMockRecorder) NodeConnect(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NodeConnect", reflect.TypeOf((*MockFreeplaneClientInterface)(nil).NodeConnect), varargs...)
}

// NodeDetailsSet mocks base method.
func (m *MockFreeplaneClientInterface) NodeDetailsSet(ctx context.Context, in *pb.NodeDetailsSetRequest, opts ...grpc.CallOption) (*pb.NodeDetailsSetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NodeDetailsSet", varargs...)
	ret0, _ := ret[0].(*pb.NodeDetailsSetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NodeDetailsSet indicates an expected call of NodeDetailsSet.
func (mr *MockFreeplaneClientInterfaceMockRecorder) NodeDetailsSet(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NodeDetailsSet", reflect.TypeOf((*MockFreeplaneClientInterface)(nil).NodeDetailsSet), varargs...)
}

// NodeLinkSet mocks base method.
func (m *MockFreeplaneClientInterface) NodeLinkSet(ctx context.Context, in *pb.NodeLinkSetRequest, opts ...grpc.CallOption) (*pb.NodeLinkSetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NodeLinkSet", varargs...)
	ret0, _ := ret[0].(*pb.NodeLinkSetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NodeLinkSet indicates an expected call of NodeLinkSet.
func (mr *MockFreeplaneClientInterfaceMockRecorder) NodeLinkSet(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NodeLinkSet", reflect.TypeOf((*MockFreeplaneClientInterface)(nil).NodeLinkSet), varargs...)
}

// NodeNoteSet mocks base method.
func (m *MockFreeplaneClientInterface) NodeNoteSet(ctx context.Context, in *pb.NodeNoteSetRequest, opts ...grpc.CallOption) (*pb.NodeNoteSetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NodeNoteSet", varargs...)
	ret0, _ := ret[0].(*pb.NodeNoteSetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NodeNoteSet indicates an expected call of NodeNoteSet.
func (mr *MockFreeplaneClientInterfaceMockRecorder) NodeNoteSet(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NodeNoteSet", reflect.TypeOf((*MockFreeplaneClientInterface)(nil).NodeNoteSet), varargs...)
}

// NodeTagAdd mocks base method.
func (m *MockFreeplaneClientInterface) NodeTagAdd(ctx context.Context, in *pb.NodeTagAddRequest, opts ...grpc.CallOption) (*pb.NodeTagAddResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NodeTagAdd", varargs...)
	ret0, _ := ret[0].(*pb.NodeTagAddResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NodeTagAdd indicates an expected call of NodeTagAdd.
func (mr *MockFreeplaneClientInterfaceMockRecorder) NodeTagAdd(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NodeTagAdd", reflect.TypeOf((*MockFreeplaneClientInterface)(nil).NodeTagAdd), varargs...)
}

// NodeTagSet mocks base method.
func (m *MockFreeplaneClientInterface) NodeTagSet(ctx context.Context, in *pb.NodeTagSetRequest, opts ...grpc.CallOption) (*pb.NodeTagSetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NodeTagSet", varargs...)
	ret0, _ := ret[0].(*pb.NodeTagSetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NodeTagSet indicates an expected call of NodeTagSet.
func (mr *MockFreeplaneClientInterfaceMockRecorder) NodeTagSet(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NodeTagSet", reflect.TypeOf((*MockFreeplaneClientInterface)(nil).NodeTagSet), varargs...)
}

// OpenMap mocks base method.
func (m *MockFreeplaneClientInterface) OpenMap(ctx context.Context, in *pb.OpenMapRequest, opts ...grpc.CallOption) (*pb.OpenMapResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "OpenMap", varargs...)
	ret0, _ := ret[0].(*pb.OpenMapResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenMap indicates an expected call of OpenMap.
func (mr *MockFreeplaneClientInterfaceMockRecorder) OpenMap(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenMap", reflect.TypeOf((*MockFreeplaneClientInterface)(nil).OpenMap), varargs...)
}

// SetNodeText mocks base method.
func (m *MockFreeplaneClientInterface) SetNodeText(ctx context.Context, in *pb.SetNodeTextRequest, opts ...grpc.CallOption) (*pb.SetNodeTextResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetNodeText", varargs...)
	ret0, _ := ret[0].(*pb.SetNodeTextResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetNodeText indicates an expected call of SetNodeText.
func (mr *MockFreeplaneClientInterfaceMockRecorder) SetNodeText(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNodeText", reflect.TypeOf((*MockFreeplaneClientInterface)(nil).SetNodeText), varargs...)
}

// StatusInfoSet mocks base method.
func (m *MockFreeplaneClientInterface) StatusInfoSet(ctx context.Context, in *pb.StatusInfoSetRequest, opts ...grpc.CallOption) (*pb.StatusInfoSetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StatusInfoSet", varargs...)
	ret0, _ := ret[0].(*pb.StatusInfoSetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StatusInfoSet indicates an expected call of StatusInfoSet.
func (mr *MockFreeplaneClientInterfaceMockRecorder) StatusInfoSet(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatusInfoSet", reflect.TypeOf((*MockFreeplaneClientInterface)(nil).StatusInfoSet), varargs...)
}

// TextFSM mocks base method.
func (m *MockFreeplaneClientInterface) TextFSM(ctx context.Context, in *pb.TextFSMRequest, opts ...grpc.CallOption) (*pb.TextFSMResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TextFSM", varargs...)
	ret0, _ := ret[0].(*pb.TextFSMResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TextFSM indicates an expected call of TextFSM.
func (mr *MockFreeplaneClientInterfaceMockRecorder) TextFSM(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TextFSM", reflect.TypeOf((*MockFreeplaneClientInterface)(nil).TextFSM), varargs...)
}
