# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import freeplane_pb2 as freeplane__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in freeplane_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FreeplaneStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateChild = channel.unary_unary(
                '/freeplane.Freeplane/CreateChild',
                request_serializer=freeplane__pb2.CreateChildRequest.SerializeToString,
                response_deserializer=freeplane__pb2.CreateChildResponse.FromString,
                _registered_method=True)
        self.DeleteChild = channel.unary_unary(
                '/freeplane.Freeplane/DeleteChild',
                request_serializer=freeplane__pb2.DeleteChildRequest.SerializeToString,
                response_deserializer=freeplane__pb2.DeleteChildResponse.FromString,
                _registered_method=True)
        self.NodeAttributeAdd = channel.unary_unary(
                '/freeplane.Freeplane/NodeAttributeAdd',
                request_serializer=freeplane__pb2.NodeAttributeAddRequest.SerializeToString,
                response_deserializer=freeplane__pb2.NodeAttributeAddResponse.FromString,
                _registered_method=True)
        self.NodeLinkSet = channel.unary_unary(
                '/freeplane.Freeplane/NodeLinkSet',
                request_serializer=freeplane__pb2.NodeLinkSetRequest.SerializeToString,
                response_deserializer=freeplane__pb2.NodeLinkSetResponse.FromString,
                _registered_method=True)
        self.NodeDetailsSet = channel.unary_unary(
                '/freeplane.Freeplane/NodeDetailsSet',
                request_serializer=freeplane__pb2.NodeDetailsSetRequest.SerializeToString,
                response_deserializer=freeplane__pb2.NodeDetailsSetResponse.FromString,
                _registered_method=True)
        self.NodeNoteSet = channel.unary_unary(
                '/freeplane.Freeplane/NodeNoteSet',
                request_serializer=freeplane__pb2.NodeNoteSetRequest.SerializeToString,
                response_deserializer=freeplane__pb2.NodeNoteSetResponse.FromString,
                _registered_method=True)
        self.NodeTagSet = channel.unary_unary(
                '/freeplane.Freeplane/NodeTagSet',
                request_serializer=freeplane__pb2.NodeTagSetRequest.SerializeToString,
                response_deserializer=freeplane__pb2.NodeTagSetResponse.FromString,
                _registered_method=True)
        self.NodeTagAdd = channel.unary_unary(
                '/freeplane.Freeplane/NodeTagAdd',
                request_serializer=freeplane__pb2.NodeTagAddRequest.SerializeToString,
                response_deserializer=freeplane__pb2.NodeTagAddResponse.FromString,
                _registered_method=True)
        self.NodeConnect = channel.unary_unary(
                '/freeplane.Freeplane/NodeConnect',
                request_serializer=freeplane__pb2.NodeConnectRequest.SerializeToString,
                response_deserializer=freeplane__pb2.NodeConnectResponse.FromString,
                _registered_method=True)
        self.NodeAddIcon = channel.unary_unary(
                '/freeplane.Freeplane/NodeAddIcon',
                request_serializer=freeplane__pb2.NodeAddIconRequest.SerializeToString,
                response_deserializer=freeplane__pb2.NodeAddIconResponse.FromString,
                _registered_method=True)
        self.Groovy = channel.unary_unary(
                '/freeplane.Freeplane/Groovy',
                request_serializer=freeplane__pb2.GroovyRequest.SerializeToString,
                response_deserializer=freeplane__pb2.GroovyResponse.FromString,
                _registered_method=True)
        self.NodeColorSet = channel.unary_unary(
                '/freeplane.Freeplane/NodeColorSet',
                request_serializer=freeplane__pb2.NodeColorSetRequest.SerializeToString,
                response_deserializer=freeplane__pb2.NodeColorSetResponse.FromString,
                _registered_method=True)
        self.NodeBackgroundColorSet = channel.unary_unary(
                '/freeplane.Freeplane/NodeBackgroundColorSet',
                request_serializer=freeplane__pb2.NodeBackgroundColorSetRequest.SerializeToString,
                response_deserializer=freeplane__pb2.NodeBackgroundColorSetResponse.FromString,
                _registered_method=True)
        self.StatusInfoSet = channel.unary_unary(
                '/freeplane.Freeplane/StatusInfoSet',
                request_serializer=freeplane__pb2.StatusInfoSetRequest.SerializeToString,
                response_deserializer=freeplane__pb2.StatusInfoSetResponse.FromString,
                _registered_method=True)
        self.TextFSM = channel.unary_unary(
                '/freeplane.Freeplane/TextFSM',
                request_serializer=freeplane__pb2.TextFSMRequest.SerializeToString,
                response_deserializer=freeplane__pb2.TextFSMResponse.FromString,
                _registered_method=True)
        self.MindMapFromJSON = channel.unary_unary(
                '/freeplane.Freeplane/MindMapFromJSON',
                request_serializer=freeplane__pb2.MindMapFromJSONRequest.SerializeToString,
                response_deserializer=freeplane__pb2.MindMapFromJSONResponse.FromString,
                _registered_method=True)
        self.MindMapToJSON = channel.unary_unary(
                '/freeplane.Freeplane/MindMapToJSON',
                request_serializer=freeplane__pb2.MindMapToJSONRequest.SerializeToString,
                response_deserializer=freeplane__pb2.MindMapToJSONResponse.FromString,
                _registered_method=True)
        self.GetCurrentNode = channel.unary_unary(
                '/freeplane.Freeplane/GetCurrentNode',
                request_serializer=freeplane__pb2.GetCurrentNodeRequest.SerializeToString,
                response_deserializer=freeplane__pb2.GetCurrentNodeResponse.FromString,
                _registered_method=True)
        self.OpenMap = channel.unary_unary(
                '/freeplane.Freeplane/OpenMap',
                request_serializer=freeplane__pb2.OpenMapRequest.SerializeToString,
                response_deserializer=freeplane__pb2.OpenMapResponse.FromString,
                _registered_method=True)
        self.FocusNode = channel.unary_unary(
                '/freeplane.Freeplane/FocusNode',
                request_serializer=freeplane__pb2.FocusNodeRequest.SerializeToString,
                response_deserializer=freeplane__pb2.FocusNodeResponse.FromString,
                _registered_method=True)


class FreeplaneServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateChild(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteChild(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeAttributeAdd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeLinkSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeDetailsSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeNoteSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeTagSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeTagAdd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeConnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeAddIcon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Groovy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeColorSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NodeBackgroundColorSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StatusInfoSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TextFSM(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MindMapFromJSON(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MindMapToJSON(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FocusNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FreeplaneServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateChild': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateChild,
                    request_deserializer=freeplane__pb2.CreateChildRequest.FromString,
                    response_serializer=freeplane__pb2.CreateChildResponse.SerializeToString,
            ),
            'DeleteChild': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteChild,
                    request_deserializer=freeplane__pb2.DeleteChildRequest.FromString,
                    response_serializer=freeplane__pb2.DeleteChildResponse.SerializeToString,
            ),
            'NodeAttributeAdd': grpc.unary_unary_rpc_method_handler(
                    servicer.NodeAttributeAdd,
                    request_deserializer=freeplane__pb2.NodeAttributeAddRequest.FromString,
                    response_serializer=freeplane__pb2.NodeAttributeAddResponse.SerializeToString,
            ),
            'NodeLinkSet': grpc.unary_unary_rpc_method_handler(
                    servicer.NodeLinkSet,
                    request_deserializer=freeplane__pb2.NodeLinkSetRequest.FromString,
                    response_serializer=freeplane__pb2.NodeLinkSetResponse.SerializeToString,
            ),
            'NodeDetailsSet': grpc.unary_unary_rpc_method_handler(
                    servicer.NodeDetailsSet,
                    request_deserializer=freeplane__pb2.NodeDetailsSetRequest.FromString,
                    response_serializer=freeplane__pb2.NodeDetailsSetResponse.SerializeToString,
            ),
            'NodeNoteSet': grpc.unary_unary_rpc_method_handler(
                    servicer.NodeNoteSet,
                    request_deserializer=freeplane__pb2.NodeNoteSetRequest.FromString,
                    response_serializer=freeplane__pb2.NodeNoteSetResponse.SerializeToString,
            ),
            'NodeTagSet': grpc.unary_unary_rpc_method_handler(
                    servicer.NodeTagSet,
                    request_deserializer=freeplane__pb2.NodeTagSetRequest.FromString,
                    response_serializer=freeplane__pb2.NodeTagSetResponse.SerializeToString,
            ),
            'NodeTagAdd': grpc.unary_unary_rpc_method_handler(
                    servicer.NodeTagAdd,
                    request_deserializer=freeplane__pb2.NodeTagAddRequest.FromString,
                    response_serializer=freeplane__pb2.NodeTagAddResponse.SerializeToString,
            ),
            'NodeConnect': grpc.unary_unary_rpc_method_handler(
                    servicer.NodeConnect,
                    request_deserializer=freeplane__pb2.NodeConnectRequest.FromString,
                    response_serializer=freeplane__pb2.NodeConnectResponse.SerializeToString,
            ),
            'NodeAddIcon': grpc.unary_unary_rpc_method_handler(
                    servicer.NodeAddIcon,
                    request_deserializer=freeplane__pb2.NodeAddIconRequest.FromString,
                    response_serializer=freeplane__pb2.NodeAddIconResponse.SerializeToString,
            ),
            'Groovy': grpc.unary_unary_rpc_method_handler(
                    servicer.Groovy,
                    request_deserializer=freeplane__pb2.GroovyRequest.FromString,
                    response_serializer=freeplane__pb2.GroovyResponse.SerializeToString,
            ),
            'NodeColorSet': grpc.unary_unary_rpc_method_handler(
                    servicer.NodeColorSet,
                    request_deserializer=freeplane__pb2.NodeColorSetRequest.FromString,
                    response_serializer=freeplane__pb2.NodeColorSetResponse.SerializeToString,
            ),
            'NodeBackgroundColorSet': grpc.unary_unary_rpc_method_handler(
                    servicer.NodeBackgroundColorSet,
                    request_deserializer=freeplane__pb2.NodeBackgroundColorSetRequest.FromString,
                    response_serializer=freeplane__pb2.NodeBackgroundColorSetResponse.SerializeToString,
            ),
            'StatusInfoSet': grpc.unary_unary_rpc_method_handler(
                    servicer.StatusInfoSet,
                    request_deserializer=freeplane__pb2.StatusInfoSetRequest.FromString,
                    response_serializer=freeplane__pb2.StatusInfoSetResponse.SerializeToString,
            ),
            'TextFSM': grpc.unary_unary_rpc_method_handler(
                    servicer.TextFSM,
                    request_deserializer=freeplane__pb2.TextFSMRequest.FromString,
                    response_serializer=freeplane__pb2.TextFSMResponse.SerializeToString,
            ),
            'MindMapFromJSON': grpc.unary_unary_rpc_method_handler(
                    servicer.MindMapFromJSON,
                    request_deserializer=freeplane__pb2.MindMapFromJSONRequest.FromString,
                    response_serializer=freeplane__pb2.MindMapFromJSONResponse.SerializeToString,
            ),
            'MindMapToJSON': grpc.unary_unary_rpc_method_handler(
                    servicer.MindMapToJSON,
                    request_deserializer=freeplane__pb2.MindMapToJSONRequest.FromString,
                    response_serializer=freeplane__pb2.MindMapToJSONResponse.SerializeToString,
            ),
            'GetCurrentNode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentNode,
                    request_deserializer=freeplane__pb2.GetCurrentNodeRequest.FromString,
                    response_serializer=freeplane__pb2.GetCurrentNodeResponse.SerializeToString,
            ),
            'OpenMap': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenMap,
                    request_deserializer=freeplane__pb2.OpenMapRequest.FromString,
                    response_serializer=freeplane__pb2.OpenMapResponse.SerializeToString,
            ),
            'FocusNode': grpc.unary_unary_rpc_method_handler(
                    servicer.FocusNode,
                    request_deserializer=freeplane__pb2.FocusNodeRequest.FromString,
                    response_serializer=freeplane__pb2.FocusNodeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'freeplane.Freeplane', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('freeplane.Freeplane', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Freeplane:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateChild(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freeplane.Freeplane/CreateChild',
            freeplane__pb2.CreateChildRequest.SerializeToString,
            freeplane__pb2.CreateChildResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteChild(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freeplane.Freeplane/DeleteChild',
            freeplane__pb2.DeleteChildRequest.SerializeToString,
            freeplane__pb2.DeleteChildResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NodeAttributeAdd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freeplane.Freeplane/NodeAttributeAdd',
            freeplane__pb2.NodeAttributeAddRequest.SerializeToString,
            freeplane__pb2.NodeAttributeAddResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NodeLinkSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freeplane.Freeplane/NodeLinkSet',
            freeplane__pb2.NodeLinkSetRequest.SerializeToString,
            freeplane__pb2.NodeLinkSetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NodeDetailsSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freeplane.Freeplane/NodeDetailsSet',
            freeplane__pb2.NodeDetailsSetRequest.SerializeToString,
            freeplane__pb2.NodeDetailsSetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NodeNoteSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freeplane.Freeplane/NodeNoteSet',
            freeplane__pb2.NodeNoteSetRequest.SerializeToString,
            freeplane__pb2.NodeNoteSetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NodeTagSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freeplane.Freeplane/NodeTagSet',
            freeplane__pb2.NodeTagSetRequest.SerializeToString,
            freeplane__pb2.NodeTagSetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NodeTagAdd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freeplane.Freeplane/NodeTagAdd',
            freeplane__pb2.NodeTagAddRequest.SerializeToString,
            freeplane__pb2.NodeTagAddResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NodeConnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freeplane.Freeplane/NodeConnect',
            freeplane__pb2.NodeConnectRequest.SerializeToString,
            freeplane__pb2.NodeConnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NodeAddIcon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freeplane.Freeplane/NodeAddIcon',
            freeplane__pb2.NodeAddIconRequest.SerializeToString,
            freeplane__pb2.NodeAddIconResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Groovy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freeplane.Freeplane/Groovy',
            freeplane__pb2.GroovyRequest.SerializeToString,
            freeplane__pb2.GroovyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NodeColorSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freeplane.Freeplane/NodeColorSet',
            freeplane__pb2.NodeColorSetRequest.SerializeToString,
            freeplane__pb2.NodeColorSetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NodeBackgroundColorSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freeplane.Freeplane/NodeBackgroundColorSet',
            freeplane__pb2.NodeBackgroundColorSetRequest.SerializeToString,
            freeplane__pb2.NodeBackgroundColorSetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StatusInfoSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freeplane.Freeplane/StatusInfoSet',
            freeplane__pb2.StatusInfoSetRequest.SerializeToString,
            freeplane__pb2.StatusInfoSetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TextFSM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freeplane.Freeplane/TextFSM',
            freeplane__pb2.TextFSMRequest.SerializeToString,
            freeplane__pb2.TextFSMResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MindMapFromJSON(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freeplane.Freeplane/MindMapFromJSON',
            freeplane__pb2.MindMapFromJSONRequest.SerializeToString,
            freeplane__pb2.MindMapFromJSONResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MindMapToJSON(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freeplane.Freeplane/MindMapToJSON',
            freeplane__pb2.MindMapToJSONRequest.SerializeToString,
            freeplane__pb2.MindMapToJSONResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freeplane.Freeplane/GetCurrentNode',
            freeplane__pb2.GetCurrentNodeRequest.SerializeToString,
            freeplane__pb2.GetCurrentNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freeplane.Freeplane/OpenMap',
            freeplane__pb2.OpenMapRequest.SerializeToString,
            freeplane__pb2.OpenMapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FocusNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/freeplane.Freeplane/FocusNode',
            freeplane__pb2.FocusNodeRequest.SerializeToString,
            freeplane__pb2.FocusNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
